### ISSUE TITLE
[Feature Request] Support offline logging

### ISSUE THREAD

**Issue by ynie** [amplitude/Amplitude-iOS#10]
Cache all the events if the device is offline. Send out all the events if the user come back online.

**Comment by allanca** [comment]
Hi ynie, 

Thanks for the suggestion. The SDK already has logic to do offline queuing. If you're seeing issues with it, please let us know.

**Comment by srounce** [comment]
@allanca Is the queue size adjustable?

**Comment by djih** [comment]
@srounce you should be able to. The queue size is saved under [Amplitude instance].eventMaxCount, and the default value is 1000. So after you initialize you can modify that value, something like this:

[[Amplitude instance] initializeApiKey:apiKey];
[Amplitude instance].eventMaxCount = 500;
