### ISSUE TITLE
upgradePrefs call guaranteed nil destination

### ISSUE THREAD

**Issue by maxrose** [amplitude/Amplitude-iOS#102]
Having some issues with old users' migrating to the newer version of amplitude.

Inside of the initWithInstanceName: there is a call to upgradePrefs which is dependent on the _propertyListPath and _eventsDataPath being set. Otherwise the copyItemAtPath:toPath:error: with crash with a nil destination exception. However, the _eventsDataPath isn't set until after the upgradePrefs call is done and released immediately.

Not sure what the best solution would be. Perhaps splitting up the upgradePrefs call to two separate calls to reflect the different dependencies?

Thanks for your help!

**Comment by djih** [comment]
@maxrose thank you for reporting the issue we are working on a patch now, will release before end of week

**Comment by djih** [comment]
@maxrose patch has been pushed with [v3.7.1](https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.7.1), please update and sorry for the crashes

**Comment by maxrose** [comment]
great! thanks @djih
