### ISSUE TITLE
Getting crashes on iOS 10

### ISSUE THREAD

**Issue by aryaxt** [amplitude/Amplitude-iOS#120]
``` Amplitude_iOS
__51-[AMPDatabaseHelper inDatabaseWithStatement:block:]_block_invoke

#0
Crashed: com.amplitude.db.queue
SIGABRT ABORT 0x000000018fffa014

Crashed: com.amplitude.db.queue
0  libsystem_kernel.dylib         0x18fffa014 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1900c1460 pthread_kill + 112
2  libsystem_c.dylib              0x18ff6e3f4 abort + 140
3  libsystem_malloc.dylib         0x19003ea38 _nano_vet_and_size_of_live + 330
4  libsystem_malloc.dylib         0x19003fdb8 nano_free + 220
5  libsqlite3.dylib               0x19159f6f8 (null) + 2552
6  libsqlite3.dylib               0x1915a5924 (null) + 1204
7  Amplitude_iOS                  0x10161cbf0 __51-[AMPDatabaseHelper inDatabaseWithStatement:block:]_block_invoke + 224
8  libdispatch.dylib              0x18feb51c0 _dispatch_client_callout + 16
9  libdispatch.dylib              0x18fec2860 _dispatch_barrier_sync_f_invoke + 84
10 Amplitude_iOS                  0x10161caa0 -[AMPDatabaseHelper inDatabaseWithStatement:block:] + 228
11 Amplitude_iOS                  0x10161e774 -[AMPDatabaseHelper getValueFromTable:key:] + 276
12 Amplitude_iOS                  0x1016269e8 -[Amplitude optOut] + 60
13 Amplitude_iOS                  0x101622cd4 __117-[Amplitude logEvent:withEventProperties:withApiProperties:withUserProperties:withGroups:withTimestamp:outOfSession:]_block_invoke + 52
14 Foundation                     0x191aed7e4 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
15 Foundation                     0x191a32358 -[NSBlockOperation main] + 96
16 Foundation                     0x191a22954 -[__NSOperationInternal _start:] + 620
17 Foundation                     0x191aefb90 __NSOQSchedule_f + 228
18 libdispatch.dylib              0x18feb51c0 _dispatch_client_callout + 16
19 libdispatch.dylib              0x18fec3444 _dispatch_queue_serial_drain + 928
20 libdispatch.dylib              0x18feb89a8 _dispatch_queue_invoke + 652
21 libdispatch.dylib              0x18fec538c _dispatch_root_queue_drain + 572
22 libdispatch.dylib              0x18fec50ec _dispatch_worker_thread3 + 124
23 libsystem_pthread.dylib        0x1900bd2c8 _pthread_wqthread + 1288
24 libsystem_pthread.dylib        0x1900bcdb4 start_wqthread + 4
```

**Comment by djih** [comment]
@aryaxt thanks for reporting! How often/many times are you seeing this crash?

**Comment by aryaxt** [comment]
Here is the crashlytics report
<img width="1197" alt="screen shot 2016-10-29 at 8 05 34 am" src="https://cloud.githubusercontent.com/assets/3460069/19830973/57b1ff4e-9db4-11e6-954c-465029911485.png">

**Comment by djih** [comment]
@aryaxt yep we're looking into it. Something changed in iOS 10 with regards to ARC and ref counting I think, which is causing this crash

**Comment by djih** [comment]
@aryaxt I'm wondering if its related to this: https://github.com/amplitude/Amplitude-iOS/issues/100. I'm going to push a patch for that today. How did you guys work around that build error?

**Comment by aryaxt** [comment]
@djih we did not have a build error, thanks will update to the latest version and see if it fixes the issue

**Comment by lexrus** [comment]
I was using 3fdd8f3c635ea12916dfe21d84267e56f1936b0e for more than 1 month and everything works fine. But after upgrading to the latest 3.10.1, the app keeping crash on my iOS 10.1.1 iPhone. My app was wrote in Swift, I can't address the issue even in debug mode.

**Comment by aryaxt** [comment]
hmm looks like the crash is not happening anymore. Will keep an eye on it for a while
<img width="1208" alt="screen shot 2016-11-06 at 10 42 58 am" src="https://cloud.githubusercontent.com/assets/3460069/20040510/0cf86ea6-a40e-11e6-8e39-a191ad8838b6.png">

**Comment by djih** [comment]
@aryaxt thanks for the update

@lexrus that's weird. The only thing that changed in 3.10.1 was setting build setting "weak references in manual retain release" to true: https://github.com/amplitude/Amplitude-iOS/commit/041f2baed7888186c9bddcffba4728ef2762ba11. That's needed because Xcode 7.3 and Xcode 8 will give build errors without the flag. Any more information you can provide?
