### ISSUE TITLE
AMPRevenue. Price for other currencies?

### ISSUE THREAD

**Issue by banshchikov** [amplitude/Amplitude-iOS#122]
Hi there! 

For now if you want to track revenue you can only use "USD" currency. Is it possible to track revenue in other currencies (e.g. CHF, RUB)? SKProduct contains price only in local currency.

**Comment by djih** [comment]
@banshchikov you will need to do the currency conversion yourself before sending the data to Amplitude. See the important note: https://github.com/amplitude/Amplitude-iOS#tracking-revenue
