### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by biancaFarcas** [amplitude/Amplitude-iOS#134]
Hi,
 I was trying to integrate Amplitude in my React-Native app but i receive this error:
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_Amplitude", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386

I have to mention that at some point it was working, but not anymore.

**Comment by djih** [comment]
@biancaFarcas we don't officially support React-native, but I can try to help. How are you integrating it into React-native? When you say it was working at one point, do you know which SDK version that was?

**Comment by biancaFarcas** [comment]
First, thank you for your help. I used the las version of amplitude. About integration, I put the Amplitude sub-folder in the root of my project, added -lsqlite3.0 to Other Linker Flags and imported amplitude header in my AppDelegate.

**Comment by haoliu-amp** [comment]
Sorry to keep this open for this long, we can use our js agent to instrument react native apps now.
https://help.amplitude.com/hc/en-us/articles/115001361248-JavaScript-SDK-Installation
