### ISSUE TITLE
Is macOS expected to be supported?

### ISSUE THREAD

**Issue by numen31337** [amplitude/Amplitude-iOS#138]
It has been a long time since this library was released and there is still no support for macOS. For companies that support versions of applications for iOS and macOS, this imposes certain difficulties in the support of several analytic systems. Are there any plans to eliminate this shortcoming?

**Comment by philippb** [comment]
I opened a PR a while ago. We never managed to get it in. 
We had Amplitude working fine with OSX. See : https://github.com/amplitude/Amplitude-iOS/pull/74

**Comment by lovette** [comment]
I'd love to see official support for macOS too. In general, it feels like vendors are giving up on desktop app analytics solutions. Mixpanel [announced macOS support](https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.1.2) in March, so maybe the tide will turn.

**Comment by nikolaenkoag** [comment]
Is there any news about macOS support in Amplitude?

**Comment by rob-keepsafe** [comment]
We've added a PR for this here, based off the latest version 4.04: https://github.com/amplitude/Amplitude-iOS/pull/155

**Comment by haoliu-amp** [comment]
Thanks for your contribution for macOS. We decide to support it next year. Before supporting it, we need to make sure we can support it. e.g. Building a macOS app to integrate.

**Comment by haoliu-amp** [comment]
Hey! I have PR #225 for macOS support (with @rob-keepsafe help), but I do not get enough time to fully test it. 

If any of you wanna try this out, really appreciate! And give me feedback please!

**Comment by haoliu-amp** [comment]
It's supported now. 
https://github.com/amplitude/Amplitude-iOS/releases/tag/v5.0.0
