### ISSUE TITLE
APP Extension- Error-sharedapplication is unavailable:not available on ios(App extension)

### ISSUE THREAD

**Issue by santhoshrajs** [amplitude/Amplitude-iOS#140]
Hi ,
I am using pod file to install amplitude framework for both app and extension.
 pod 'Amplitude-iOS', '~> 3.7.0'

Once i install i am getting error in Amplitude.m.
sharedapplication is unavailable:not available on ios(App extension)
Could any one help me how to use Amplitude for app extension.

**Comment by djih** [comment]
Hi @santhoshrajs we did not add support for extensions until v3.8.0: https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.8.0. But I highly recommend updating to our latest version v3.14.1: https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.14.1
