### ISSUE TITLE
App Extension -Issue 

### ISSUE THREAD

**Issue by santhoshrajs** [amplitude/Amplitude-iOS#141]
Hi ,
@djih 
As you said i have updated to 3.8.0 i am able to use the sdk for both app and app extension.
but the events from app extension not reflecting in dashboard.Kindly help me

**Comment by haoliu-amp** [comment]
We're not sure if our SDK will work with App Extension since we don't target on it. Closing this for now since it's an old ticket. Pls reopen if you have other concerns.
