### ISSUE TITLE
[NSFileManager copyItemAtPath:toPath:options:error:]: destination path is nil

### ISSUE THREAD

**Issue by jaimevz27** [amplitude/Amplitude-iOS#142]
Hello,

Im using Segment-Amplitude SDK to send data to Amplitude but there is some session tracking issue that requires to include Amplitude-iOS SDK too. We include the library and everything was working fine with our beta testers, but when my app went into production, some users started to experience crashes. 

I'm writing you guys because i couldn't figure out what is causing this error. it happens with some users at the moment. my app users have the same features so i would think it should be affecting everyone of them, but it s not. There wasn't errors until i include Amplitude-iOS SDK.  Hopefully you can point me in right direction and solve this issue. 

these are the pods versions i'm using at the moment

Segment-Amplitude (1.2.0):
    - Amplitude-iOS (~> 3.6.0)
    - Analytics (~> 3.0.7)

This is my basic implementation in AppDelegate

let segmentConfig : SEGAnalyticsConfiguration = SEGAnalyticsConfiguration(writeKey: SegmentWriteKey)
let segmentAmplitude : SEGAmplitudeIntegrationFactory = SEGAmplitudeIntegrationFactory.instance()
segmentConfig.use(segmentAmplitude)
SEGAnalytics.setupWithConfiguration(segmentConfig)

This is the error log from crashlytics:

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x19085afd8 __exceptionPreprocess
1  libobjc.A.dylib                0x18f2bc538 objc_exception_throw
2  CoreFoundation                 0x19085af20 -[NSException initWithCoder:]
3  Foundation                     0x1912f8e04 -[NSFileManager copyItemAtPath:toPath:options:error:]
4  Degusta                        0x1007d4314 -[Amplitude moveFileIfNotExists:to:] (Amplitude.m:1527)
5  Degusta                        0x1007d3ce4 -[Amplitude upgradePrefs] (Amplitude.m:1435)
6  Degusta                        0x1007ce1a4 __34-[Amplitude initWithInstanceName:]_block_invoke (Amplitude.m:250)
7  Foundation                     0x191329804 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
8  Foundation                     0x19126e760 -[NSBlockOperation main]
9  Foundation                     0x19125eb18 -[__NSOperationInternal _start:]
10 Foundation                     0x19132bba0 __NSOQSchedule_f
11 libdispatch.dylib              0x18f7129a0 _dispatch_client_callout
12 libdispatch.dylib              0x18f720ad4 _dispatch_queue_serial_drain

![screen shot 2017-04-13 at 8 15 30 am](https://cloud.githubusercontent.com/assets/10619595/25008741/3675f576-202a-11e7-8a9d-8d477316880a.png)

**Comment by djih** [comment]
This was patched in [v3.7.1](https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.7.1). Please update your Segment-Amplitude integration. The latest version will use v3.14.0 of Amplitude's iOS SDK
