### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by azeff** [amplitude/Amplitude-iOS#144]
Hey.

I've seen a couple crashes in swift code:
```swift
let device = ApiDeviceInfo(timezone: timezone,
                           token: token,
                           amplitudeDeviceId: Amplitude.instance().deviceId)
```

Where timezone and token are `String`, i.e. are not optional values, and `ApiDeviceInfo` is simple struct.
```swift
struct ApiDeviceInfo {
  let timezone: String
  let token: String
  let amplitudeDeviceId: String
}
```

So, the only thing that can crash here is `Amplitude.instance().deviceId`, moreover crashlogs point to exact line `amplitudeDeviceId: Amplitude.instance().deviceId)`.

The above code is executed in `applicationDidBecomeActive`. We do `Amplitude.instance().initializeApiKey(apiKey)` in AppDelegate's `didFinishLaunchingWithOptions`.

Crash can happen if `Amplitude.instance()` or `Amplitude.instance().deviceId` return `nil`. I'm wondering in which situations this can happen. Can't find this in the docs and there are no Obj-C nullability annotation in Amplitude sdk code. Which means that from Swift almost everything is accessible as implicitly unwrapped optionals, which is unsafe ([Nullability and Optionals](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-ID45))

Do you have any ideas?

**Comment by djih** [comment]
@azeff I think it might be a timing issue. The deviceId is only available after the SDK is initialized, which happens on a background thread so that it doesn't block your app's main thread. The issue with that is that it's hard to guarantee when that deviceId will be available to the main thread. We will need to investigate a little more. Have you tried reading the deviceId from somewhere other than `applicationDidBecomeActive`?

**Comment by azeff** [comment]
@djih thanks for response. It may indeed be a timing issue. We have not tried to read `deviceId` anywhere else, need to review this peace anyways.

Do you plan to annotate ObjC code?

**Comment by haoliu-amp** [comment]
We're trying to clean up all the old tickets. Going to close this now. Pls open it if you still experience it.
