### ISSUE TITLE
Xcode 9.0.1 / Swift 4 Compiler Warning

### ISSUE THREAD

**Issue by harelw** [amplitude/Amplitude-iOS#157]
I am using Amplitude-iOS 4.0.4 via CocoaPods 1.4.0.beta.2 and `platform :ios, '10.0'`

Deployment target for iOS project is also set to 10.0

The following is the Xcode compiler warning:
> .../Pods/Amplitude-iOS/Amplitude/Amplitude.m:1661:46: 'unarchiveTopLevelObjectWithData:error:' is only available on iOS 9.0 or newer

**Comment by zmian** [comment]
There are tons of warning in Xcode 9.3

<img width="392" alt="screen shot 2018-05-08 at 8 15 48 pm" src="https://user-images.githubusercontent.com/621693/39789238-a73cc342-52fc-11e8-89b3-d7d5c79a6408.png">

**Comment by zmian** [comment]
thank you @djih!
