### ISSUE TITLE
Crash in AMPDatabaseHelper.m line 195

### ISSUE THREAD

**Issue by harryblam** [amplitude/Amplitude-iOS#159]
I am using Amplitude-iOS (4.0.4).

Crashlytics reported an crash today as:
_Crashed: com.amplitude.db.queue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000009_

I cannot reproduce this issue, however will attach the crash report
[AMPDatabaseHelper  crash export.txt](https://github.com/amplitude/Amplitude-iOS/files/1753918/AMPDatabaseHelper.crash.export.txt)

**Comment by harryblam** [comment]
Just seen this happening when testing on simulator also! See screenshot for exception breakpoint.
<img width="1181" alt="screen shot 2018-02-27 at 18 23 23" src="https://user-images.githubusercontent.com/2333536/36712292-0494bd66-1bed-11e8-8a4f-d5d98b101c28.png">

**Comment by haoliu-amp** [comment]
#229
