### ISSUE TITLE
Offline event cache

### ISSUE THREAD

**Issue by maradic** [amplitude/Amplitude-iOS#161]
Is there any built in option to cache events when i'm offline? I could not found it in documentation?

**Comment by djih** [comment]
@maradic events are logged to a database table on the device and uploaded in batches. If the upload succeeds, those events are cleared from the table. If the device is offline and cannot upload events, they will continue to log to the database until connection is re-established. There is a default limit of 1000 unsent events allowed in the table, after which it will start dropping events starting from the oldest events.

**Comment by maradic** [comment]
@djih thank you. Is there any time limit beside number limit?

**Comment by djih** [comment]
@maradic no time limit. The unsent events should remain unless the user clears app data or uninstalls.
