### ISSUE TITLE
Amplitude-iOS pod produce a lot of warnings

### ISSUE THREAD

**Issue by IuriiIaremenko** [amplitude/Amplitude-iOS#164]
Amplitude-iOS v4.2.0 pod produce a lot (57 issues in particular) of warnings:
> Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

We are using swift 4.1 in our project and trying to keep clean build.

**Comment by djih** [comment]
Thanks for reporting! Expect this fix to go out soon: https://github.com/amplitude/Amplitude-iOS/pull/165
