### ISSUE TITLE
App Store Connect issues a warning for usage of location APIs without a purpose string

### ISSUE THREAD

**Issue by jaltreuter** [amplitude/Amplitude-iOS#168]
My app has included this library for many releases now, without issue.  Today though when I submitted an update to App Store Connect, I received an automated warning.  I've quoted it at the bottom here, but effectively it says that we're accessing user location data and should provide NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription keys to explain why we need this user data.

The only reference to CLLocation I know of in our app is [within Amplitude](https://github.com/amplitude/Amplitude-iOS/search?q=cllocation&unscoped_q=cllocation), [for example here](https://github.com/amplitude/Amplitude-iOS/blob/d5785f7fe043ac3a229294726697a0d93ddc77ae/Amplitude/Amplitude.m#L322).

While location data from Amplitude is useful, we have no need for it in the rest of our app so I would prefer not to have to include a request for that permission.  Is Amplitude aware of this issue with the iOS SDK, and does it have a plan to offer a workaround?

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "Otter Voice Notes". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> "Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."
> 
> "Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
> 
> Best regards,
> 
> The App Store Team

**Comment by genadyo** [comment]
Same here 😥

**Comment by djih** [comment]
@jaltreuter @genadyo you can disable location listening in our iOS SDK by calling `[[Amplitude instance] disableLocationListening]` before `initializeWithApiKey`. Would that be enough to get around the automated warning?

**Comment by jaltreuter** [comment]
@djih unfortunately no, I just tried that now and got the same warning message from App Store Connect.  I think they just check for references to CLLocation anywhere as opposed to performing static analysis on the binary.

**Comment by seanchoe** [comment]
I'm literally dealing with this issue right now too 😁

**Comment by jaltreuter** [comment]
To be clear, as best I can tell this warning isn't going to block the release of our app (although I haven't submitted for review since I started getting the warning) and no location permission prompt is shown when running the app.  @seanchoe have you run into any issues beyond just a warning?

The reason I've filed an issue is because my app has no valid reason to ask for users' locations, so there isn't anything reasonable I could put in my Info.plist for those purpose strings.  While I haven't seen any prompts show up so far, the fact that it lies out of my control is worrisome.

**Comment by seanchoe** [comment]
@jaltreuter Yes, it's just a warning for now, but it seems Apple will force it starting in spring 2019.

I think there are two options now, before Amplitude could have a version without the location code.

1. You just add the purpose string. As long as you don't use the location service, the users of your app won't see this message I think.
2. Fork this repository, and remove the location code.

For our app we've already forked, so I think we can remove the location code. I haven't tried it yet but hopefully it works!

**Comment by mhoeller-clue** [comment]
Seems like Apple started enforcing this now. Our latest build was rejected.

**Comment by jaltreuter** [comment]
@mhoeller-clue at what point(s) in the submission process did your build get warnings or failures?

I hadn't noticed until just now, but in early September 2018 I stopped getting these warnings about my builds, despite changing nothing about my Amplitude integration or updating the cocoapod (I've been on version 4.2.1 since May 2018).  I've successfully submitted many app updates since then, the latest of which was ~2.5 weeks ago, and up until today I haven't gotten any more warning emails.  Today, having still not changed anything about Amplitude, I uploaded (but did not submit) a build to App Store Connect.  When it finished processing I got pretty much the exact same warning email that I pasted in my original comment here.  As in the original message, it says:

> Your delivery was successful, but you may wish to correct the following issues in your next delivery

Ordinarily I would expect this means we won't have any issue submitting our app, but maybe you experienced differently?

**Comment by mhoeller-clue** [comment]
@jaltreuter We started to get the warning with the build we uploaded on the 1st of April. The only places CoreLocation is used are the Amplitude SDK and the Facebook SDK.

**Comment by jaltreuter** [comment]
@mhoeller-clue just to make sure I understand correctly, you got just a warning when you uploaded the build, but when you submitted it for review it got rejected?  How have you mitigated that issue?  I'll be submitting a build for review soon and would like to reduce back-and-forth with the reviewers, so your insight is very helpful.

**Comment by mhoeller-clue** [comment]
After uploading we got the email with the error message. We could not add the build to the upcoming @jaltreuter release, so we were not able to submit for review.
We fixed the issue by adding both NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription to info.plist. Because the value for those keys can't be empty or only a whitespace, we just put an emoji for now.

**Comment by jaltreuter** [comment]
@mhoeller-clue just to share another data point, my app submission was approved despite the warning email.  My app doesn't have the Facebook SDK, so maybe that contains different code that increases the severity of Apple's response.  Thanks again for sharing your experience!

**Comment by haoliu-amp** [comment]
Hey all! now location information is customer driven since v7.0.0. Please give it a try. Thanks!

https://developers.amplitude.com/docs/location-tracking
