### ISSUE TITLE
Feature Request: Method to set app version

### ISSUE THREAD

**Issue by dkpalmer** [amplitude/Amplitude-iOS#170]
We have an iPhone app built with React Native that we push updates to using a service called Code Push. When we push Code Push updates, we would like to associate all Amplitude events in that code to a different Version than the actual binary. E.g.

1) We release '1.0' to the App Store. The version associated with events in Amplitude is '1.0'
2) We push '1.0 update 1' over Code Push. We would like to change the version for new events in Amplitude to '1.0 update 1'. (Note: the binary is still version '1.0', we're just running some updated code on top of it via Code Push.

Would this be possible with the Amplitude iOS SDK?

**Comment by dkpalmer** [comment]
Bump. Any chance something like this is possible?

**Comment by haoliu-amp** [comment]
@dkpalmer Make sense, will discuss it internally first.

**Comment by haoliu-amp** [comment]
@dkpalmer Could you just log the version as an event property on every event instead? It looks like a very special case.

**Comment by haoliu-amp** [comment]
Close this for now.
