### ISSUE TITLE
SQLite connection object leaked when sqlite3_open fails

### ISSUE THREAD

**Issue by numist** [amplitude/Amplitude-iOS#172]
Unless the system is out of memory, `sqlite3_open` will always return a connection object regardless of success. From the [SQLite website](https://www.sqlite.org/c3ref/open.html):

> Whether or not an error occurs when it is opened, resources associated with the database connection handle should be released by passing it to sqlite3_close() when it is no longer required.

I haven't checked every `sqlite3_open` call site, but it looks like the error path in `-[AMPDatabaseHelper inDatabaseWithStatement:block:]` returns without calling `sqlite3_close`.

**Comment by djih** [comment]
@numist thanks for reporting, we will patch this in next update

**Comment by numist** [comment]
Fixed in #190
