### ISSUE TITLE
Pod Version 4.4.0 not released or updated in cocoapods

### ISSUE THREAD

**Issue by mobile-ar** [amplitude/Amplitude-iOS#176]
Pod Version 4.4.0 not released or updated in `cocoapods`

```
CocoaPods could not find compatible versions for pod "Amplitude-iOS":
  In Podfile:
    Amplitude-iOS (~> 4.4.0)
```

Last released version is `4.0.4` from `October 23, 2017`

**Comment by djih** [comment]
@mobile-ar  are you on an older version of Cocoapods?
4.4.0 is released and updated in Cocoapods: https://cocoapods.org/pods/Amplitude-iOS

I was able to verify in our test app:
```
Daniels-MacBook-Pro:iOS-Demo daniel$ pod install
Analyzing dependencies
Downloading dependencies
Installing Amplitude-iOS 4.4.0 (was 4.3.1)
```
