### ISSUE TITLE
Can't include iOS framework

### ISSUE THREAD

**Issue by NanyiJiang** [amplitude/Amplitude-iOS#177]
Followed the tutorial, added amplitude via carthage. compiles. I only added the line `import Amplitude` in our code so far. Program crashes on launch:

<img width="1127" alt="screen shot 2018-10-25 at 12 21 41 pm" src="https://user-images.githubusercontent.com/9128661/47515571-39e41680-d851-11e8-90c2-297c0e73a0db.png">
digged around and found this answer:

<img width="981" alt="screen shot 2018-10-25 at 12 22 33 pm" src="https://user-images.githubusercontent.com/9128661/47515610-53855e00-d851-11e8-998d-53e4983c9dbb.png">

but we don't even have "embedded binaries" section in our project, Xcode 10
<img width="1146" alt="screen shot 2018-10-25 at 12 21 56 pm" src="https://user-images.githubusercontent.com/9128661/47515615-5a13d580-d851-11e8-8e02-190d0388c824.png">

**Comment by djih** [comment]
@NanyiJiang the embedded binaries and frameworks section should be under the `SnapTravel` target under the `General` tab.

The Carthage documentation has instructions for adding frameworks to your iOS application: https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

Alternatively you can also use Cocoapods to install our iOS SDK, and that process is simpler and more straight forward
