### ISSUE TITLE
Feature Request : Detect session id changes before they occur

### ISSUE THREAD

**Issue by ghugues** [amplitude/Amplitude-iOS#180]
## Problem
We are trying to count the number of occurrences of some events within a session, and add this information as a property of these events.

For example, let's say we have some events categorized as "page views". For all the events we send (including events that are not page views) we want to include as a property how many page views have occurred within the current session. This would result in something like this :
```
* App is launched, a new session is started (Session 1)
 - 1. Application launch event (not a page view)
   - properties : { "page views count": 0 }
 - 2. Some event (not a page view)
   - properties : { "page views count": 0 }
 - 3. Viewed page A event
   - properties : { "page views count": 1 }
 - 4. Viewed page B event
   - properties : { "page views count": 2 }
 - 5. Some event (not a page view)
   - properties : { "page views count": 2 }
 - 6. Application goes to background and stays in background until the session times out
* App is launched, a new session is started (Session 2)
 - 7. Application launch event
   - properties : { "page views count": 0 }
 - 8. Viewed page C event
   - properties : { "page views count": 1 }
```
In order to implement this, we need to maintain an internal count and reset it to zero when a new session is started. What we currently do is we save the session id using the `getSessionId` method. Before each event we send, we call `getSessionId` again. If the session id has changed, we reset the count to zero.

The problem is that `getSessionId` doesn't renew the session id if it needs to (it just returns the value of the ivar). Only sending an event actually refreshes the session id. So in step 7, when we query the session id for comparison with our stored value, it hasn't changed yet. So we don't reset our internal count and `"page views count"` is set to `2` (although event 7 will correctly be part of session 2).
Since logging event 7 triggers a refresh of the session id, when we get the session id for event 8, it has changed so we reset the internal count and `"page views count"` is correctly set to `1`.

To sum up, to first event of each session (except the first one) always gets an invalid count.

## Feature Request

In order to make this work, **we need to know when the next event we send will be part of a new session**.
Here are some ways this could be done :
 1. Make the `-(BOOL)startOrContinueSession:(long long)timestamp` method part of the public API. This is the simplest approach since this method does exactly what we want to do.
 2. Call `-(BOOL)startOrContinueSession:(long long)timestamp` in `getSessionId`. But this is potentially a breaking change.
 3. Make `_lastEventTime` a public property or `- (BOOL)isWithinMinTimeBetweenSessions:(long long)timestamp` a public method (basically allowing to know when `-(BOOL)startOrContinueSession:(long long)timestamp` will refresh the session id)

Note : If you consider adding this feature to the iOS SDK, please consider also adding it to the Android SDK since we have this problem on Android as well.

**Comment by ghugues** [comment]
Hi,
I never received any feedback on this request. Is this not the right way to bring up issues ?
@djih

**Comment by djih** [comment]
@ghugues apologies for the delay, I'm assuming you're at Le Monde? I have contacted your CSM and we will follow up with this feature request. Thanks!

**Comment by ghugues** [comment]
Hi @djih
Yes I'm at Le Monde. Thank you for following up with this request.

**Comment by ghugues** [comment]
Hi @djih
Any news on this request ?

**Comment by dana11235** [comment]
We have logged this request, and are considering it for the future.

**Comment by djih** [comment]
@ghugues thank you for your patience. We will do the first suggestion you made (making `startOrContinueSession` public. I just want you to know that if you call that method, you will potentially trigger the SDK to start a new session. It's not just a method to fetch the status of session changing.

**Comment by ghugues** [comment]
Hi @djih 
Better late than never: thank you for the release of this feature. I'm closing the issue.
Would you consider doing the same on Android ? Making `boolean startNewSessionIfNeeded(long timestamp)` public (https://github.com/amplitude/Amplitude-Android/blob/db9dfdd99c2149b4b97dc516c99bf10585ab2b98/src/com/amplitude/api/AmplitudeClient.java#L1178) ?
I can duplicate this issue on the Android repo if needed.

**Comment by djih** [comment]
@ghugues expect the Android equivalent to go out by EOD: https://github.com/amplitude/Amplitude-Android/pull/195

**Comment by djih** [comment]
@ghugues v2.23.0 is released (might take some time to sync to Maven). Thank you for your patience: https://github.com/amplitude/Amplitude-Android/releases/tag/v2.23.0

**Comment by ghugues** [comment]
@djih Thanks a lot for your work.
