### ISSUE TITLE
Unable to Carthage build for tvOS

### ISSUE THREAD

**Issue by makangus** [amplitude/Amplitude-iOS#184]
I am getting an error trying to carthage build for tvOS 
`Dependency "Amplitude-iOS" has no shared framework schemes for any of the platforms: tvOS`

**Comment by haoliu-amp** [comment]
I can't reproduce it.

**Comment by honcheng** [comment]
<img width="301" alt="Screenshot 2020-03-25 at 2 22 59 PM" src="https://user-images.githubusercontent.com/208827/77507825-256fd780-6ea4-11ea-8421-5a91685365b7.png">

The shared schemes for tvOS and macOS are not pushed to the repo. I'm also encountering the problem for Mac. Just turn off and on the shared option for tvOS and macOS and the *.xcscheme file will be regenerated.

**Comment by haoliu-amp** [comment]
@honcheng Thank you for reminding us! I've added those.
