### ISSUE TITLE
[iOS] Log event on app crash

### ISSUE THREAD

**Issue by BrunoBerisso** [amplitude/Amplitude-iOS#19]
Hi,

I wonder if there is a way to log an event when my app crash for some reason (signal or unhandled exception). I check the web and the SDK code but didn't find a way.

Call any `logEvent:` method doesn't work because this methods work asynchronously and the app is terminated before the events are saved.

Thanks

**Comment by djih** [comment]
@BrunoBerisso : our SDK doesn't have any crash support. You probably want to use something like Crashlytics for that
