### ISSUE TITLE
How to log event property with empty value?

### ISSUE THREAD

**Issue by gerchicov-bp** [amplitude/Amplitude-iOS#195]
Swift:
`Amplitude.instance().logEvent("SomeEvent", withEventProperties: ["SomeKey": ""])`
works like "event with not properties" and there is no info about avoiding passing empty strings as values in the official documentation.
Is there an official way to post empty string (or other empty value) to amplitude? Or maybe is it a bug?

**Comment by haoliu-amp** [comment]
We don't support logging empty value.
