### ISSUE TITLE
App close event can not be tracked

### ISSUE THREAD

**Issue by rintoandrews90** [amplitude/Amplitude-iOS#200]
I have tried to tack on app close. but event log not found in amplitude. I am able see all other events in dashboard

please check code given

```swift
func applicationWillTerminate(_ application: UIApplication) {
    Amplitude.instance()?.logEvent("APP_CLOSED")
}
```

**Comment by iwasrobbed** [comment]
Just an FYI: `applicationWillTerminate` is not guaranteed to be called in an app unless you opt out of multitasking support. (Just google `applicationWillTerminate not called` and you'll see the countless caveats for when/how it might be called)

It's not a metric I would rely upon and you're safer putting something in a backgrounding/foregrounding callback for sessions.

From [the docs](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623111-applicationwillterminate)
>For apps that do not support background execution or are linked against iOS 3.x or earlier, this method is always called when the user quits the app. For apps that support background execution, this method is generally not called when the user quits the app because the app simply moves to the background in that case. However, this method may be called in situations where the app is running in the background (not suspended) and the system needs to terminate it for some reason.

**Comment by haoliu-amp** [comment]
I think @iwasrobbed is right on this. It might not be achievable. However, we will add feature for users to be able to track some automatic events later this year.
