### ISSUE TITLE
Please support Swift Package Manager

### ISSUE THREAD

**Issue by sjmueller** [amplitude/Amplitude-iOS#203]
Now that Xcode 11 has reached GM Seed, the seamless integration of Swift Package Manager into the IDE undoubtedly makes it the preferred installation method.

Please consider adding support for `amplitude-ios`, thanks.

**Comment by claudiogomezGL** [comment]
Hi @sputh @blazzy, is there any chance we can have the SPM support in the near future?

**Comment by haoliu-amp** [comment]
Hey guys, please refer to #213 to see the progress.

**Comment by haoliu-amp** [comment]
Change has been merged.
