### ISSUE TITLE
[iOS 13] Crash on NSLog statements for SSL pinning

### ISSUE THREAD

**Issue by rob-keepsafe** [amplitude/Amplitude-iOS#204]
Hi there 👋 

We're seeing some crashes in iOS 13 for `NSLog` statements within `ISPCertificatePinning`: https://github.com/amplitude/Amplitude-iOS/blob/master/Amplitude/SSLCertificatePinning/ISPCertificatePinning.m#L58

👉 This was actually our largest crash in production.

We went ahead and commented out all of the `NSLog` statements for now. These should ideally be wrapped in a `DEBUG` check anyways.

<img width="793" alt="Screen Shot 2019-09-09 at 2 36 06 PM" src="https://user-images.githubusercontent.com/30269720/64987014-44a70000-d896-11e9-88f2-93ea98aaf161.png">

**Comment by sputh** [comment]
This is resolved per https://github.com/amplitude/Amplitude-iOS/pull/205

**Comment by rob-keepsafe** [comment]
Thanks @sputh !
