### ISSUE TITLE
Can't build app for ArmV7 - ld: library not found for -lAmplitude-iOS

### ISSUE THREAD

**Issue by Aequitas737** [amplitude/Amplitude-iOS#210]
With `Build Active Architecture Only: No` and `Valid Architectures: arm64, armv7s, arm64e and armv7` I keep getting an error on building:

```
ld: warning: directory not found for option '-L/Users/.../ios/Pods/Amplitude-iOS/iOS'
ld: library not found for -lAmplitude-iOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Nothing I try can resolve this, except for removing the `armv7` option for the valid architectures (and a bit of other messing around). Does the `Amplitude-iOS` library not support armv7? or am I missing something?

**Comment by Aequitas737** [comment]
I think it's got to do with the deployment version. Resolved by increasing deployment version to `11`

**Comment by chellongCoder** [comment]
@Aequitas737 you save my day 🥰
