### ISSUE TITLE
Support for Proxy Configuration

### ISSUE THREAD

**Issue by pierre-wehbe** [amplitude/Amplitude-iOS#212]
Hello Team, 

We have clients using proxy for security purposes, I could support that by modifying the Amplitude.m file, but we do not want to do that.
Would it be possible for you to expose an initializer that allows passing a custom NSURLSession or NSURLSessionConfiguration?

Thank you

**Comment by haoliu-amp** [comment]
Hi, can you give me more details about your request? e.g. Which api are we talking about now? What kind of change are you proposing?

**Comment by pierre-wehbe** [comment]
Hi @haoliu-amp ,

I am developing an iOS application using latest Swift 5.1, pod 'Amplitude-iOS', '>= 4.5.0'.

Our application is designed for Businesses, some of which have proxy enabled that causes Amplitude api calls to be blocked.

I would like a function to inject a custom NSURLSessionConfiguration that will contain our proxy settings (username password, host, port). We should also be able to change these configuration while the application is running by probably accessing the shared instance of Amplitude.

Let me know what you think.

**Comment by haoliu-amp** [comment]
I personally think this is a valid case. We will discuss about it internally.

**Comment by haoliu-amp** [comment]
Hey @pierre-wehbe , 

We do have a feature to support this already I think.

Amplitude’s SDKs provide options that allow events to be sent to an alternative server endpoint. You can use setServerUrl to configure the server url.

You can find the api in Amplitude.h.

**Comment by haoliu-amp** [comment]
Close this since we already support it.
