### ISSUE TITLE
v2.2.3 broke AMPLocationManagerDelegate

### ISSUE THREAD

**Issue by saniul** [amplitude/Amplitude-iOS#22]
Specifically, [this](https://github.com/amplitude/Amplitude-iOS/blob/master/Amplitude/AMPLocationManagerDelegate.m#L22) crashes since `Amplitude` doesn’t have a class method `updateLocation` anymore.

/cc @curtisliu

**Comment by curtisliu** [comment]
Thanks catching this! Fixed and added a test for this as well.
