### ISSUE TITLE
Contributors Recognition Initiative

### ISSUE THREAD

**Issue by haoliu-amp** [amplitude/Amplitude-iOS#226]
To all the contributors (who helped us change the code),

We want to thank and recognize all the contributors by putting their names on our README file.

Let us know if you're interested, please reach out to hao.liu@amplitude.com.

Thanks!
-Amplitude

**Comment by rob-keepsafe** [comment]
This is a good effort 👍 I will say historically this repo has been a place where issues and PRs go to quietly die and I think the best recognition you could ever give is to improve triaging and communication with your customers and community.

**Comment by haoliu-amp** [comment]
@rob-keepsafe Thanks, that's what we're working on right now. Thank you for your past contributions too.
