### ISSUE TITLE
SSL pinning failing even though certs are found

### ISSUE THREAD

**Issue by rob-keepsafe** [amplitude/Amplitude-iOS#228]
Hi there 👋 

It seems you all might have swapped out your root certificates or something else broke in your SSL pinning check since it's failing and not logging any events from the app. All of our metrics took a nosedive in the past couple of days even though we hadn't released an update in a couple of months.

The obvious workaround for now is to disable SSL pinning, but we'd appreciate you all investigating this since I'd imagine it might impact other customers as well.

<img width="936" alt="Screen Shot 2020-02-18 at 8 55 53 AM" src="https://user-images.githubusercontent.com/30269720/74769753-0dff5800-522f-11ea-929d-4f77ad86afe0.png">

<img width="1537" alt="Screen Shot 2020-02-18 at 9 01 02 AM" src="https://user-images.githubusercontent.com/30269720/74769765-15266600-522f-11ea-9610-213c8dd6c31d.png">

**Comment by haoliu-amp** [comment]
Just be notified that old certificate got expired. Actively working on this now. Try to find the best solution for it. The worst case is that to update SDK.

**Comment by rob-keepsafe** [comment]
Thanks @haoliu-amp 👍 As long as the root certificates weren't changed, this should have continued working like normal even if the `api.amplitude.com` certificate expired (since the root certs don't expire for another 10+ years). Seems like the root certs were invalidated though so this will likely break everyone

**Comment by rob-keepsafe** [comment]
For the time being, we're disabling SSL pinning in the podfile by setting `AMPLITUDE_SSL_PINNING=0` and this falls back to using `URLSession`:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable Amplitude SSL pinnning
      # https://amplitude.zendesk.com/hc/en-us/articles/115002278527-iOS-SDK-Installation#ssl-pinning
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AMPLITUDE_SSL_PINNING=0']
    end
  end
end
```

e.g.

<img width="1313" alt="Screen Shot 2020-02-18 at 10 06 49 AM" src="https://user-images.githubusercontent.com/30269720/74776356-7eac7180-523b-11ea-85ca-782175790d8e.png">

**Comment by haoliu-amp** [comment]
@rob-keepsafe , now it's back to normal. Sorry for the inconvenience.

**Comment by rob-keepsafe** [comment]
Thank you @haoliu-amp ; we'll confirm on our end after the events come in
