### ISSUE TITLE
Umbrella header 'AmplitudeFramework.h' not found

### ISSUE THREAD

**Issue by SergeMaslyakov** [amplitude/Amplitude-iOS#233]
Hi. 

I use Carthage. Caught it when updated on v5.0.0.

**Comment by haoliu-amp** [comment]
Hey, did you use umbrella header somewhere in your project?

**Comment by SergeMaslyakov** [comment]
My project is on swift and I use it in `Bridging-Header.h` as

```
#import <Amplitude/Amplitude.h>
```

**Comment by haoliu-amp** [comment]
That error doesn't happen to me. I create a sample app integrated with 5.0.0 with Carthage. You can check this out.

https://drive.google.com/file/d/1WjwBRmV8E01EuM8jJNDI-22bg6Es9I7A/view?usp=sharing

**Comment by SergeMaslyakov** [comment]
Hi! Thanks for a test project.
I have checked it out.

I noticed that you have added `Amplitude` explicitly in the embedded frameworks tab in `General`.
Plus you have added `Carthage` step in Build Phases tab.

If I do the same (explicitly add framework in embedded) my project will be compiled too. 

But it isn't my way. I didn't add my frameworks explicitly. I do it thru `Carthage` step in `Build Phases` tab only.

I have modified your test project. I have removed explicitly added framework and then I roll it back to `v4.10.0` - it compiles. Then I just changed version in Cartfile to `v5.0.0` and run `carthage update --platform ios --no-use-binaries --cache-builds`. As result - It doesn't compile.
Modified project by this [https://drive.google.com/file/d/1VawFfrrHqEpr2guCce5Vby3JfZ6owLyS/view?usp=sharing](https://drive.google.com/file/d/1VawFfrrHqEpr2guCce5Vby3JfZ6owLyS/view?usp=sharing)

So, anyway thanks for your time. In general It isn't a problem, I can use v.4.10.0 and it works.

**Comment by SergeMaslyakov** [comment]
@haoliu-amp

I think the problem is that `AmplitudeFramework.h` is in `Project headers`.

I had added `AmplitudeFramework.h` in `Public header` in target `Amplitude-iOS` then have built with Carthage. Everything is now OK - now I see `AmplitudeFramework.h` in exposed headers in `Amplitude.framework`.

I don't have any idea why it worked earlier - maybe because `Amplitude-iOS` didn't consist 'Private headers' before v5.0.0.

**Comment by haoliu-amp** [comment]
@SergeMaslyakov I see, so it's missing `AmplitudeFramework.h`, look like some how Carthage build doesn't include the umbrella header. Umbrella header is pretty much a file only includes all the public headers. That's what it does.

What you can do now, is to just import the necessary headers from Amplitude instead of using umbrella header.

Also, I'm debating if we should keep the umbrella header in the future.

**Comment by haoliu-amp** [comment]
Going to close this for now. Thanks for reaching out.

**Comment by sumac13** [comment]
Can this be fixed inside the SDK so that the below changes are made and we can use carthage without having to make any custom change to our build process so that it works like 4.10.0 did

> @haoliu-amp
> 
> I think the problem is that `AmplitudeFramework.h` is in `Project headers`.
> 
> I had added `AmplitudeFramework.h` in `Public header` in target `Amplitude-iOS` then have built with Carthage. Everything is now OK - now I see `AmplitudeFramework.h` in exposed headers in `Amplitude.framework`.
> 
> This commit [https://github.com/SergeMaslyakov/Amplitude-iOS](https://github.com/SergeMaslyakov/Amplitude-iOS/commit/b8b7dba49e5acafd49d8a2af9ecf85e1ccdd705e)
> 
> I don't have any idea why it worked earlier - maybe because `Amplitude-iOS` didn't consist 'Private headers' before v5.0.0.
