### ISSUE TITLE
Expired cert raises flag in some security checks

### ISSUE THREAD

**Issue by tikimcfee** [amplitude/Amplitude-iOS#235]
Hey there folks, thanks much for your time. This issue is in regards to a similar thread, #228. A target project of ours utilizing Amplitude has been found to include the expired cert. For the sake of our continued usage, the team is hoping you would be able to offer some knowledge about it, how it's being used, et al. Specifically, it would be a great bullet-list for us to communicate back to our curious minds with these:

- How does the certificate impact day-to-day usage of the Amplitude SDK?
- Is it possible for a 3rd party (us) to remove the certificate if necessary?
- Is there an updated version of Amplitude that may already have an updated cert; if not, should we look forward to one soon?

Again, thanks for your time on this. Looking to get this bit of info tidied up and filed away for good on our end; please feel free to ask anything else in return.

**Comment by haoliu-amp** [comment]
Hey!
Please check https://status.amplitude.com/incidents/dxtdykzr6s25 for further information. This incident explained what happened.

To answer your questions.
1. Our certificate will expire in 10 years, so it won't have any impact on day2day usage.
2. If you choose NOT to use SSL pinning feature, then yes.
3. We don't need to update the cert. The authority updated our cert by mistake, but it was reverted back.

**Comment by haoliu-amp** [comment]
Hey,

Which certificate is expired? Could you give me the file name of it?

**Comment by tikimcfee** [comment]
Hey there @haoliu-amp, thanks for getting back so quickly!

The cert we're seeing is `api.amplitude.com.der` -> https://github.com/amplitude/Amplitude-iOS/blob/master/Sources/Amplitude/api.amplitude.com.der 

From the notes mentioned, it seems like the cert was looked at again because of an authority making an incorrect change to your chain, which meant you had to take that up with them yourself. While I don't think we were exposed to the pinning issue (I don't think pinning is defaulted to 'on', is it?), we do have some eyes on the age of the cert itself.

Cert info:
<img height="300" alt="BasicCertInfo" src="https://user-images.githubusercontent.com/3186605/76887926-3c794e80-6840-11ea-9b4a-d8b257437eb3.png">

**Comment by haoliu-amp** [comment]
I see, this one is actually not being used for SSL pinning, so we will remove it.

The ones currently under used, are `ComodoRsaCA` and `ComodoRsaDomainValidationCA`.

**Comment by tikimcfee** [comment]
Cool cool, a little early Spring cleaning. Looks like `ComodoRsaCA.der` also expires **May, 2020** - I think you mentioned it's unused, but just a heads up anyway.

Once this is all settled down, think this will basically be a version-bump on our Cocoapod side?

**Comment by haoliu-amp** [comment]
Yes, that's correct! @tikimcfee

**Comment by haoliu-amp** [comment]
Sorry for the long wait, we just removed the outdated certs.
