### ISSUE TITLE
Can't use Amplitude v5 with Carthage on Swift project

### ISSUE THREAD

**Issue by hontd** [amplitude/Amplitude-iOS#241]
Hey there, when I upgrade Amplitude to v5.1.0 by Carthage, I encounter this error when compiling:

../Amplitude.framework/Modules/module.modulemap:2:21: Umbrella header 'AmplitudeFramework.h' not found

When I check the above path, `AmpltidueFramework.h` file is actually missing.

My project used to work fine with v4.10.0. Am I doing something wrong? Please help me on this issue? Thanks.

**Comment by PintoDiaz** [comment]
Check https://github.com/amplitude/Amplitude-iOS/issues/233, but I'm not sure which is the best solution right now.

**Comment by hontd** [comment]
Cool, thanks. I’ll close this one as it’s duplicated.

**Comment by haoliu-amp** [comment]
@hontd If you guys still wanna keep the umbrella header, I will make a change to include it later.

**Comment by hthi-atlassian** [comment]
@haoliu-amp Any fix inside the framework will be appreciated. Thanks.

**Comment by hontd** [comment]
@haoliu-amp yeah, that would be good. Thanks.

**Comment by haoliu-amp** [comment]
@hontd @PintoDiaz @hthi-atlassian 
I just merged a fix but I haven't created new release yet.
If you wanna try it out, you can do
```
git "https://github.com/amplitude/Amplitude-iOS.git" "master"
```

**Comment by PintoDiaz** [comment]
Trying it out! Thank you very much!!

**Comment by hthi-atlassian** [comment]
Thanks @haoliu-amp !
