### ISSUE TITLE
iOS10.3.* crashes in AMPDatabaseHelper

### ISSUE THREAD

**Issue by ZaVyLoN** [amplitude/Amplitude-iOS#245]
Cocoapods: Amplitude-iOS (4.10.0) - last version.
Users (iPhone 5 iOS 10.3.* ) still have this crash.

How can I fix this problem?

**Comment by ZaVyLoN** [comment]
<img width="545" alt="Screen Shot 2020-04-29 at 21 17 51" src="https://user-images.githubusercontent.com/3078481/80631842-080fc980-8a5f-11ea-82c7-094341b84457.png">
<img width="542" alt="Screen Shot 2020-04-29 at 21 18 05" src="https://user-images.githubusercontent.com/3078481/80631862-0e9e4100-8a5f-11ea-85b3-ae8774d3bf61.png">
<img width="545" alt="Screen Shot 2020-04-29 at 21 18 16" src="https://user-images.githubusercontent.com/3078481/80631865-11009b00-8a5f-11ea-9a7f-e7db37a869dc.png">

**Comment by haoliu-amp** [comment]
Hey, does this only happen for iPhone 5?

**Comment by ZaVyLoN** [comment]
@haoliu-amp, hello.

1.  iPhone 5 (Model A1428) - 10.3.4 (14G61)
2. iPhone 5c (Model A1456, A1532) - 10.3.3 (14G60)
3. iPad (4th generation Model A1459) - 10.3.4 (14G61)
4. iPhone 5 (Model A1429) - 10.3.4 (14G61)

**Comment by haoliu-amp** [comment]
Thank you! We will investigate soon.

**Comment by haoliu-amp** [comment]
@ZaVyLoN Also I saw AMPSqliteStore appearing from the stack traces. Does it also use sqlite library?

**Comment by ZaVyLoN** [comment]
@haoliu-amp, yes.

**Comment by haoliu-amp** [comment]
<img width="545" alt="80631842-080fc980-8a5f-11ea-82c7-094341b84457" src="https://user-images.githubusercontent.com/57638692/81219511-bf8f6900-8f94-11ea-8f38-289f95ba7980.png">
So was this the moment that the crash happen? I tried to get it reproduced but I can't on iPhone 5 simulator.

**Comment by ZaVyLoN** [comment]
Found out that the problem is related to another library, firebase.
Thanks for the help.

**Comment by haoliu-amp** [comment]
@ZaVyLoN That's one possibilities that we thought yesterday. Could you let me know how did you fix it? What triggered this crash? Mutli-thread accessing sqlite at the same time? Or it's a problem related to 32 bit on iPhone 5?

**Comment by ZaVyLoN** [comment]
I can not reproduce on my devices. Unfortunately. I suggested that this is due to
https://github.com/firebase/firebase-ios-sdk/issues/5508

I updated Firebase to 6.24.0 and I will watch for such crashes.
