### ISSUE TITLE
[Question] Is it possible to configure the dispatch to happen now?

### ISSUE THREAD

**Issue by zeitos** [amplitude/Amplitude-iOS#246]
Hi all,
    We are working on test automation and we would like to be able to configure the app so it sends all notifications immediately during QA, is that possible?

**Comment by haoliu-amp** [comment]
You mean flushing all events? e.g. `flushEvent`?

**Comment by zeitos** [comment]
Yes, Ideally I would like to flush after each event in a configurable way, since this if for Testing I don't want to fill the code with `if QA flush`

**Comment by haoliu-amp** [comment]
We will add one soon. Probably next week.

**Comment by haoliu-amp** [comment]
@zeitos Also, you could change `eventUploadThreshold` to 0, so that you get every event submitted immediately.
https://github.com/amplitude/Amplitude-iOS/blob/master/Sources/Amplitude/Amplitude.h#L90
