### ISSUE TITLE
watchOS support

### ISSUE THREAD

**Issue by martindaum** [amplitude/Amplitude-iOS#247]
Sorry to bring this up again, but how can this not be on your roadmap? If you have a standalone Watch app, this is a must have and for us it would be the reason to switch to a competitor able to track our users on the Watch. 

With standalone watch apps it is not possible to take the route via iPhone app anymore and watchOS also introduced subscriptions, which makes it important to track events as you will be able to generate revenue by optimizing stuff.

**Comment by haoliu-amp** [comment]
@martindaum Thanks for your feedback. We are thinking to add it to our Q3 roadmap.

**Comment by mohammad-rahchamani** [comment]
@martindaum take a look at Watchlitude  https://github.com/mohammad-rahchamani/Watchlitude . WatchOS library for Amplitude.
