### ISSUE TITLE
Got +[Amplitude updateLocation]: unrecognized selector sent to class ...

### ISSUE THREAD

**Issue by SergeMaslyakov** [amplitude/Amplitude-iOS#248]
Hi.

I just updated Amplitude sdk for my project (I use a master branch to avoid problem with Carthage).

I got this error

```
"Uncaught NSException: +[Amplitude updateLocation]: unrecognized selector sent to class 0x10422eeb8"
```

Commit `github "amplitude/Amplitude-iOS" "b6e80e296b7355a1b9b65e8e6fc4038c88f35775"`

**Comment by haoliu-amp** [comment]
@SergeMaslyakov Hello, sorry, it's because I removed some deprecated APIs which are really old.
You should use member function instead. Static ones were deprecated.
```
/**
 Forces the SDK to update with the user's last known location if possible.

 If you want to manually force the SDK to update with the user's last known location, call updateLocation.
 */
- (void)updateLocation;
```

**Comment by SergeMaslyakov** [comment]
So, the problem is I don't invoke this method directly. It happens during initialisation SDK when an User opt-out from analytics. I think it's s missed invocation inside SDK.

```
     amplitude.setUserId(nil)
     amplitude.clearUserProperties()
     amplitude.optOut = true
     amplitude.setOffline(true)
```

**Comment by haoliu-amp** [comment]
Oh, my bad. This function shouldn't be removed. I added it back. Thank you for reporting it to us. Would you like to try it again?

**Comment by SergeMaslyakov** [comment]
I have checked it. Now it's OK.

Thanks
