### ISSUE TITLE
use MD5 will cause integrate failed.

### ISSUE THREAD

**Issue by blzhu** [amplitude/Amplitude-iOS#250]
call CC_MD5 in md5HexDigest, when we integrate Amplitude,  scanning tool report this defect,  it easy to fix, but if have this defect , our app can not integrate Amplitude for security concern. hope you fix it .

**Comment by haoliu-amp** [comment]
Thanks, we will look into it.

**Comment by haoliu-amp** [comment]
This crypto algorithm is used for our checksum field, actually you don't need to worry about the security concern for that. However, we will see if we wanna switch it to SHA256.

**Comment by blzhu** [comment]
great, we very much hope it switch to SHA256 .  I know this crypto algorithm is not for security use, but scan report tool will still show it in report  , some customer will have security concern for that,  explain it will also have poor effective ，and competitor will also make waves in market

**Comment by JanNash** [comment]
Hey @haoliu-amp, is there an update on a possible switch to SHA256? I'd gladly submit a PR to update the CC_MD5 usage to SHA256 in this framework. I'd also gladly fix the other two deprecation warnings in said PR.

**Comment by haoliu-amp** [comment]
@JanNash Thanks for your help contributing and I need to work with our backend team to make changes there to coordinate with this change. However, you can submit a PR for sure. 

Thanks again.

**Comment by JanNash** [comment]
> Thanks again.
No worries :)
