### ISSUE TITLE
SwiftPM: ISPPinnedNSURLConnectionDelegate.h' file not found when enabling SSL pinning

### ISSUE THREAD

**Issue by okalentiev** [amplitude/Amplitude-iOS#252]
I'm trying to switch the installation to the SwiftPM and experiencing issues if I switch the `AMPLITUDE_SSL_PINNING` on.

This happens in `AMPURLConnection.h` file on line 27. 

Am I doing something wrong or this is an issue? I suspect that it might be happening because the files in the `SSLCertificatePinning` folder are private.

**Comment by haoliu-amp** [comment]
#253 

It's fixed. You can give it a try by pointing to `master` branch.

You can also enable SSL pinning by adding the following preprocessor macro:

AMPLITUDE_SSL_PINNING=1
