### ISSUE TITLE
Can not upload data from mainland, China 

### ISSUE THREAD

**Issue by zyphs21** [amplitude/Amplitude-iOS#257]
Hello, We found that we can't upload data to Amplitude from mainland, China. Are there any solutions?

**Comment by haoliu-amp** [comment]
Please direct all the traffic to `api.amplitude.com` by calling `setServerUrl`. If you wanna know more details about this issue, please create a ticket in our help center. https://help.amplitude.com/hc/en-us/requests/new

**Comment by grzegorzkrukowski** [comment]
After we redirected everything to `api2.amplitude.com` - nothing is working anymore - there are no events visible on development.

**Comment by grzegorzkrukowski** [comment]
In case anyone else will struggle with this, here is full working code:
`[[Amplitude instance] setServerUrl:@"https://api2.amplitude.com/"];`

Passing just `api2.amplitude.com` is not working.

**Comment by Asupercat** [comment]
It’s not workink

**Comment by haoliu-amp** [comment]
@Asupercat May I know how do you set it up?
