### ISSUE TITLE
About Amplitude.h setDeviceId: couldn't be used by swift

### ISSUE THREAD

**Issue by JJingLee** [amplitude/Amplitude-iOS#259]
As title, setDeviceId: would be recognized as a setter signature by swift, and deviceId is a readonly property, so that I couldn't use it through "setDeviceId:" interface. 
I could set it through "setValue:byKey:" though, it's not quite a good way I think.

**Comment by haoliu-amp** [comment]
Thank you for reporting it. For now one possible solution is to call this function in objc, and using bridging header to include it.
