### ISSUE TITLE
Change host to api2.amplitude.com

### ISSUE THREAD

**Issue by PhilippeCuvillier** [amplitude/Amplitude-iOS#260]
Hello Amplitude Team,

as follow up to the Chinese outage (see issue #257), could the SDK use http://api2.amplitude.com/ instead of http://api.amplitude.com/ as base URL?
Is there any reason _not_ to do so?
Many data have been lost, without any mean to recover beside waiting for Chinese users to update the app.

Thanks a lot.

**Comment by haoliu-amp** [comment]
Hello @PhilippeCuvillier , 

We're working on a new feature to dynamically adjust the url in SDK itself based on user's IP (geo location). With this, it should help this kind situation in the long run.

We will discuss if we wanna change the default value from api to api2.

**Comment by haoliu-amp** [comment]
it's changed to api2 by default now
