### ISSUE TITLE
Readonly properties hide setters from Swift

### ISSUE THREAD

**Issue by tzahola** [amplitude/Amplitude-iOS#282]
The `userId` and `deviceId` properties are declared as `readonly` in `Amplitude.h`:
```
/**
 Identifier for the current user.
 */
@property (nonatomic, copy, readonly) NSString *userId;

/**
 Identifier for the current device.
 */
@property (nonatomic, copy, readonly) NSString *deviceId;
```
Yet further down they also have setter methods declared:
```
/**
 Sets the userId.
 @param userId                  If your app has its own login system that you want to track users with, you can set the userId.
 @see [Setting Custom UserIds](https://github.com/amplitude/Amplitude-iOS#setting-custom-user-ids)
 */

- (void)setUserId:(NSString*) userId;
...
/**
 Sets the deviceId.

 **NOTE: not recommended unless you know what you are doing**

 @param deviceId                  If your app has its own system for tracking devices, you can set the deviceId.

 @see [Setting Custom Device Ids](https://github.com/amplitude/Amplitude-iOS#custom-device-ids)
 */
- (void)setDeviceId:(NSString*) deviceId;
```
These setter methods are inaccessible from Swift, because the ObjC→Swift bridging mechanism seems to prefer the `readonly` qualifier on the properties, thus hiding the setter methods.

## Expected Behavior
It should be possible to set the `userId` and `deviceId` properties from Swift.
## Current Behavior

It is not possible to set the `userId` and `deviceId` properties from Swift, because the setter methods are hidden by the `readonly` qualifiers at the property declarations.

## Possible Solution
Either rename these methods so they don't get mistaken for setters of readonly properties, or make the properties `readwrite` so they can be set from Swift using regular property assignment.

## Steps to Reproduce
Try calling `setUserId()` or `setDeviceId()` from Swift.

## Environment
- SDK Version: v6.0.0
- Device: any
- OS Version: any

**Comment by deRonbrown** [comment]
Related to #286, should these properties also be nullable?

**Comment by vovander** [comment]
Have the same problem ;(

**Comment by degterev** [comment]
Faced with same problem on 7.1.0 and 7.0.1

**Comment by tzahola** [comment]
By the way, my workaround was creating an extension that re-declares the setters as methods, and exposing that to Swift:
```
// NB(zaza): until this issue gets fixed https://github.com/amplitude/Amplitude-iOS/issues/282
@interface Amplitude (Hacks)

- (void)hack_setUserId:(NSString* _Nullable)userId;
- (void)hack_setDeviceId:(NSString* _Nullable)deviceId;

@end

@implementation Amplitude (Hacks)

- (void)hack_setUserId:(NSString* _Nullable)userId {
    [self setUserId:userId];
}

- (void)hack_setDeviceId:(NSString* _Nullable)deviceId {
    [self setDeviceId:deviceId];
}

@end
```
Then you'll be able to call `amplitude.hack_setUserId(userId)` from Swift.

**Comment by margulan9** [comment]
Have the same problem on 7.1.0

**Comment by jooohhn** [comment]
Thanks for the report, looking to get a fix out today

**Comment by jooohhn** [comment]
Doing a v7.1.1 release today that will include this fix
