### ISSUE TITLE
Make location block to return nullable dictionary

### ISSUE THREAD

**Issue by GRiMe2D** [amplitude/Amplitude-iOS#285]
## Summary

Amplitude v7.0.0 added location block for providing user location manually. But location isn't available instantaneously. For some moment location will be unknown. But new added location block doesn't mark it nullable however it checks for nil while accepting it. Can't return nil in swift 

https://github.com/amplitude/Amplitude-iOS/blob/d7f81d3ca3aa2d00ba83f1095857e808faaa43de/Sources/Amplitude/Amplitude.h#L32

https://github.com/amplitude/Amplitude-iOS/blob/d7f81d3ca3aa2d00ba83f1095857e808faaa43de/Sources/Amplitude/Amplitude.m#L664-L669

## Proposed
```diff
 NS_ASSUME_NONNULL_BEGIN
 
 typedef NSString *_Nonnull (^AMPAdSupportBlock)(void);
-typedef NSDictionary *_Nonnull (^AMPLocationInfoBlock)(void);
+typedef NSDictionary *_Nullable (^AMPLocationInfoBlock)(void);
```

**Comment by haoliu-amp** [comment]
Thanks for reporting the issue! 
We released v7.0.1 to address it!
https://github.com/amplitude/Amplitude-iOS/releases/tag/v7.0.1

**Comment by john-mejia** [comment]
@haoliu-amp would it be possible to call out breaking changes in future release notes? This caused a breaking change in our application and we had to dig through the PR/code to get an understanding of exactly what went wrong.

**Comment by haoliu-amp** [comment]
@john-mejia Sorry for your trouble with new changes. We did mark it to be BREAKING CHANGES in v7.0.0. (We bumped it to major version 7 since it's not back compatible change.) https://github.com/amplitude/Amplitude-iOS/releases/tag/v7.0.0

**Comment by john-mejia** [comment]
woah,. my apologies - we jumped straight to .1 and missed the original update!
