### ISSUE TITLE
Can't set user ID to `nil` on logout

### ISSUE THREAD

**Issue by deRonbrown** [amplitude/Amplitude-iOS#286]
## Summary

We used to call `Amplitude.instance().setUserId(nil)` when the user logs out, but this method no longer accepts `nil`. What's the recommended approach for logout scenarios? We want to disassociate the user from the device. We were also called `Amplitude.instance().clearUserProperties()`. Does this method just clear local device state, or does it also clear all user properties in your service/dashboard?

**Comment by haoliu-amp** [comment]
Thanks for reporting the issue! 
We released v7.0.1 to address it!
https://github.com/amplitude/Amplitude-iOS/releases/tag/v7.0.1
