### ISSUE TITLE
EXC_BAD_ACCESS in Amplitude.m due to dereferencing nil after refreshing dynamic config

### ISSUE THREAD

**Issue by jaltreuter** [amplitude/Amplitude-iOS#288]
## Expected Behavior
If `Amplitude` is deallocated while dynamic config is being refreshed, the completion block should no-op.

## Current Behavior
If `Amplitude` is deallocated while dynamic config is being refreshed, the completion block will dereference nil and crash the app.

## Possible Solution
This is a snippet of the existing code in `Amplitude.m`:
```
- (void)refreshDynamicConfig {
    if (self.useDynamicConfig) {
        __weak typeof(self) weakSelf = self;
        [[AMPConfigManager sharedInstance] refresh:^{
            __strong typeof(self) strongSelf = weakSelf;
            strongSelf->_serverUrl = [AMPConfigManager sharedInstance].ingestionEndpoint;
        }];
    }
}
```
The block avoids a retain cycle by creating a weak reference to self, but incorrectly uses that reference.  If `weakSelf` becomes nil, the block will then dereference that value and crash.  It should be replaced with
```
- (void)refreshDynamicConfig {
    if (self.useDynamicConfig) {
        __weak typeof(self) weakSelf = self;
        [[AMPConfigManager sharedInstance] refresh:^{
            __strong typeof(self) strongSelf = weakSelf;
            if strongSelf == nil {
                return;
            }
            strongSelf->_serverUrl = [AMPConfigManager sharedInstance].ingestionEndpoint;
        }];
    }
}
```

## Steps to Reproduce
1. Create an instance of `Amplitude`
2. Set `useDynamicConfig` to true
3. Call `initializeApiKey`
4. Remove all references to this instance of `Amplitude`

## Environment
- SDK Version: 7.1.0
- Device: iPhone XS Simulator
- OS Version: iOS 12.0

**Comment by haoliu-amp** [comment]
Merged. Thanks!
