### ISSUE TITLE
Set Session Id programmatically

### ISSUE THREAD

**Issue by kunalbhatt** [amplitude/Amplitude-iOS#294]
## Summary
We'd like to programmatically set session Id.

## Motivations
Reason for this is if a user comes from web to app through some click funnel on web we'd like to attribute to the same session vs creating a new session. 

I have a branch ready with this change but can't push remote branches up to the repository. We just need to add this https://github.com/amplitude/Amplitude-iOS/blob/2426c4bc59855217590848f2efed1ec258cca04b/Sources/Amplitude/Amplitude.m#L1180 to the header file. 

The same should be done for android.

**Comment by haoliu-amp** [comment]
@kunalbhatt Thanks for reporting. We will take care of it.

**Comment by jooohhn** [comment]
@kunalbhatt thoughts on #312? Would like to know if this is what you're looking for
