### ISSUE TITLE
SPM Warnings ("Found 11 files which are unhandled")

### ISSUE THREAD

**Issue by jsahoo** [amplitude/Amplitude-iOS#297]
## Expected Behavior

There shouldn't be any SPM warnings.

## Current Behavior

Seeing the following warning when integrating the Amplitude SDK via SPM:
<img width="1165" alt="Screen Shot 2020-10-13 at 8 37 23 PM" src="https://user-images.githubusercontent.com/6937424/95940887-4e01e500-0d94-11eb-96cd-03a09a8767d1.png">

## Steps to Reproduce
 

1. Integrate Amplitude via SPM
2. Observe warnings in the Issue Navigator

## Environment
- SDK Version: 7.1.0
- Device: N/A
- OS Version: macOS 10.15.7
- Xcode Version: 12.0.1

**Comment by jooohhn** [comment]
Looking into a fix for this

**Comment by jaredsinclair** [comment]
Seeing the same.

**Comment by jooohhn** [comment]
Should be fixed if SDK is updated to 7.1.1, thanks for the report!

**Comment by jsahoo** [comment]
Thanks, @jooohhn!
