### ISSUE TITLE
Error building 7.1.0 on Xcode 12.2 beta 3 for tvOS

### ISSUE THREAD

**Issue by accannis** [amplitude/Amplitude-iOS#298]
I've included Amplitude-iOS using SPM. I just updated from 5.2.0 (which built just fine) to 7.1.0, which no longer builds.

I get the following build errors:

SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPInfoViewController.m:69:46: 'UIPasteboard' is unavailable: not available on tvOS
/Applications/Xcode-beta.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIPasteboard.h:32:96: 'UIPasteboard' has been explicitly marked unavailable here
SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPInfoViewController.m:70:16: 'string' is unavailable: not available on tvOS
/Applications/Xcode-beta.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIPasteboard.h:90:46: 'string' has been explicitly marked unavailable here
SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPInfoViewController.m:76:46: 'UIPasteboard' is unavailable: not available on tvOS
/Applications/Xcode-beta.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIPasteboard.h:32:96: 'UIPasteboard' has been explicitly marked unavailable here
SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPInfoViewController.m:77:16: 'string' is unavailable: not available on tvOS
/Applications/Xcode-beta.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIPasteboard.h:90:46: 'string' has been explicitly marked unavailable here
SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPEventExplorer.m:88:13: Initializing 'CGFloat' (aka 'double') with an expression of incompatible type 'id'
SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPEventExplorer.m:96:10: Assigning to 'CGFloat' (aka 'double') from incompatible type 'void'
ARC Semantic Issue Group
SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPEventExplorer.m:53:44: No known class method for selector 'barBottomOffset'
SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPEventExplorer.m:88:41: No known class method for selector 'statusBarHeight'
SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPEventExplorer.m:89:40: No known class method for selector 'barBottomOffset'

**Comment by jooohhn** [comment]
Thanks for the notice, looking into it

**Comment by jooohhn** [comment]
@haoliu-amp do you have insight? Problem seems to be introduced with event explorer and using tvOS

**Comment by jooohhn** [comment]
7.1.0 introduced an event explorer feature that's only available on iOS. Working on a fix to exclude on macOS and tvOS
