### ISSUE TITLE
Change Amplitude ID

### ISSUE THREAD

**Issue by bago2k4** [amplitude/Amplitude-iOS#30]
Hi,
i got 2 amplitude app setup that i use for the same app but on different environments (ie: production and staging).
Is it possible to call `initializeApiKey:` a second time when the environment gets switched or i have to restart the app to let the events go through the proper app and the user id reset?
Thank you

**Comment by djih** [comment]
Hi,

Unfortunately the SDKs currently don't support multiple instances on a single app. There is a shared database, so the events from the two instances would conflict and get jumbled up.

You could probably # define APIKEY based on some config option, and set it to either the production api key or staging key based on the environment.

Best,
Dan
