### ISSUE TITLE
'Amplitude' has different definitions in different modules

### ISSUE THREAD

**Issue by karanayyana** [amplitude/Amplitude-iOS#304]
I upgraded my Xcode from 11.7 to 12.01

I am experiencing an issues which is listed in this post 
https://developer.apple.com/forums/thread/658012

in my code the error is with 
'Amplitude' has different definitions in different modules; first difference is defined here found property 'userId' with type 'NSString *'

Any help?

**Comment by jooohhn** [comment]
Thanks for the report, could you tell us what version of Amplitude-iOS you're using and post a screen shot of your code where the error occurs?

**Comment by karanayyana** [comment]
Thanks for the reply. 
I am using v7.1.1 with cocoapods 
Xcode version 12.0.1

It fails on compile 
attached screenshots 
![Screen Shot 2020-10-26 at 12 57 08 PM](https://user-images.githubusercontent.com/24512236/97221918-cc925580-178a-11eb-8a8e-9b09423e3633.png)
![Screen Shot 2020-10-26 at 12 57 21 PM](https://user-images.githubusercontent.com/24512236/97221929-cef4af80-178a-11eb-8466-9a0ac78dd1c3.png)

**Comment by karanayyana** [comment]
Any luck with this issue?

**Comment by jooohhn** [comment]
Hey @karanayyana , sorry for the slow progress. I'm still trying to debug what you're getting this problem.

I tried creating a swift project and adding Amplitude to it through Cocoapods but wasn't able to see the same error. Could you add more details on how to reproduce this?

**Comment by karanayyana** [comment]
I believe its interfering with another product called Foxit, I am guessing both have variables named userid and its Objective-C based - (https://developers.foxitsoftware.com/pdf-sdk/ios/)

since its libraries that is imported with in the project, Apple is identifying the error with Amplitude.
