### ISSUE TITLE
Error building SDK v7.1.1 in a macOS app

### ISSUE THREAD

**Issue by shadone** [amplitude/Amplitude-iOS#311]
## Current Behavior

Adding Amplitude (via SPM) version 7.1.1 shows this compilation error:

> /Users/denis/Library/Developer/Xcode/DerivedData/Foobar-awgcdxfkjlfukvbohsvthoiwjurr/SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPInfoViewController.h:26:9: UIKit is not available when building for macOS. Consider using `#if !TARGET_OS_OSX` to conditionally import this framework, first importing TargetConditionals.h if necessary.
>
> /Users/denis/Library/Developer/Xcode/DerivedData/Foobar-awgcdxfkjlfukvbohsvthoiwjurr/SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/AMPEventExplorer.m:27:9: UIKit is not available when building for macOS. Consider using `#if !TARGET_OS_OSX` to conditionally import this framework, first importing TargetConditionals.h if necessary.

## Possible Solution

Downgrading back to 7.0.1 fixes the issue.

## Steps to Reproduce

1. Create a new macOS App project
2. Add Amplitude as a SPM dependency (File->Swift Packages->Add Package Dependency add `https://github.com/amplitude/Amplitude-iOS`)
3. Try to build
4. Error!

## Environment
- OS Version: macOS 10.15.4
- Xcode: 12.0.1

**Comment by jooohhn** [comment]
Thanks for the report, it's related to #298. Will try to get a fix out today
