### ISSUE TITLE
Xcode 12.5: target 'Amplitude' has invalid header layout

### ISSUE THREAD

**Issue by HunterHillegas** [amplitude/Amplitude-iOS#326]
We're pulling the library in via the Swift Package Manager support in Xcode.

Xcode 12.5b1 was released this week.

When building with this version, the Amplitude library does not build.

## Expected Behavior

The library should build correctly.

## Current Behavior

The library does not build with the latest Xcode beta:

`Showing All Messages
target 'Amplitude' has invalid header layout: umbrella header found at '.../SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/Amplitude.h', but directories exist next to it: .../SourcePackages/checkouts/Amplitude-iOS/Sources/Amplitude/Resources; consider removing them`

## Possible Solution

The fixit suggestion from Xcode suggests it's a problem with the layout of the package.

## Steps to Reproduce

1. Create a project that pulls in the library from SPM.
2. Try to build with Xcode 12.5b1.

## Environment

Xcode 12.5b1
macOS Big Sur 11.2

Xcode is configured to build 7.2.0 - Next Major.

**Comment by florianbuerger** [comment]
Still happening on Xcode 12.5 Beta 2

**Comment by jooohhn** [comment]
Thanks for the report, looking into it

**Comment by kikettas** [comment]
Is there any lead regarding this issue?

**Comment by BrentMifsud** [comment]
Having this issue as well with Xcode beta 3 on an M1 MacBook Air

**Comment by HunterHillegas** [comment]
Unfortunately we had to pull Amplitude from our project since we couldn’t build with the latest tools. We need to be able to ship betas with the tool chain that’s about to be released as public.

**Comment by BrentMifsud** [comment]
any updates on this? Xcode 12.5 is going to be released very soon.

**Comment by lapfelix** [comment]
I was able to fix this by moving the certificate to a different folder (outside of the `publicHeadersPath` folder)
https://github.com/lapfelix/Amplitude-iOS/commit/66169aa6d190f37f7d6003c87ea5bb6947356175

I'll open a PR

**Comment by haoliu-amp** [comment]
Fixed in #335 . Thanks @lapfelix

**Comment by BrentMifsud** [comment]
Awesome job with this fix.
