### ISSUE TITLE
Amplitude fails to build on Mac Catalyst target

### ISSUE THREAD

**Issue by saidsikira** [amplitude/Amplitude-iOS#327]
## Expected Behavior
Amplitude should build successfully on the Mac Catalyst target after enabling Mac support for an iOS app

## Current Behavior
The compilation fails on `#import "APMEventExplorer.h"` in `Amplitude.m` with an error: `fatal error: 'AMPEventExplorer.h' file not found`.

<img width="313" alt="Screenshot 2021-02-21 at 09 20 34" src="https://user-images.githubusercontent.com/3612892/108619745-103e5880-7427-11eb-9aae-d78a27c56d05.png">

## Steps to Reproduce
 

1. Create a new SwiftUI iOS app.
2. Enable Mac support in the target settings

<img width="513" alt="Screenshot 2021-02-21 at 09 22 44" src="https://user-images.githubusercontent.com/3612892/108619633-6f4f9d80-7426-11eb-9ac3-c1009208bbe5.png">

3. Add a dependency to `Amplitude-iOS` through Swift Package Manager 
4. Select "My Mac" as the run target and start building
5. Build fails

## Environment
- SDK Version: v7.2.2
- Device: MacBook Air (M1, 2020)
- OS Version: iOS 14.0, macOS 11.0

**Comment by jooohhn** [comment]
WIll take a look, thanks!

**Comment by jooohhn** [comment]
Related to #324
