### ISSUE TITLE
Usage of weak crypto algorithms like MD5 in Amplitude iOS SDK

### ISSUE THREAD

**Issue by KishanLal** [amplitude/Amplitude-iOS#380]
## Summary

Our Penetration testing team has identified usage of weak crypto algorithms like MD5 in Amplitude iOS SDK and logged security vulnerability. What are the plans to migrate to latest crypto algorithms? Can you please migrate to latest crypto algorithms to mitigate this?

**Recommendation**:
Do not use weak cryptographic algorithms to protect information and processes such as RC4, DES, DES3, MD5, SHA1, MD4, ECB, & CBC as well as algorithms discussed [here](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04g-Testing-Cryptography.md). For guidance on best practices in picking strong cryptography, please see OWASP's [Cryptographic Storage Cheat_Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html). Details and code snippets can be found at https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files(https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files).

## Motivations

Security Vulnerability.

**Comment by aryanamex** [comment]
any update over this issue, i am also facing this.
