### ISSUE TITLE
-[AMPIdentify set:value:] does not allow overwriting value of existing property

### ISSUE THREAD

**Issue by junjie** [amplitude/Amplitude-iOS#387]
## Expected Behavior
The [docs](http://amplitude.github.io/Amplitude-iOS/Classes/AMPIdentify.html#//api/name/set:value) for the method `-[AMPIdentify set:value:]` states that:
> Sets the value of a given user property. **If the value already exists, it will be overwritten with the new value.**

I had assumed that that means if a property changes, I could call `-set:value:` on the same `AMPIdentify` object, then update using `-[[Amplitude instance] identify:]` using the same `AMPIdentify` object.

## Current Behavior
However, setting a new value for an existing property does not actually overwrite the property. In fact, it does nothing. This seems to stem from this portion of the code:

https://github.com/amplitude/Amplitude-iOS/blob/b3411935d96c3b154753771ab32e1df501fec478/Sources/Amplitude/AMPIdentify.m#L131-L135

… which has an early exit on line 134. This basically means the call to `-[AMPIdentify set:value:]` does nothing at all when a value of said property already exist.

## Questions

1. Is this behaviour by design? Am I understanding the docs wrongly?
2. I keep the same `AMPIdentify` object, update it when there are changes to any user property, then call `-[[Amplitude instance] identify:]` to update Amplitude on these changes. Is this not the recommended way to do this? Do you recommend creating a new `AMPIdentify` object each time we need to update any property?

## Environment
- SDK Version: v8.8.0
- Device: iPhone 12 Pro
- OS Version: iOS 15.3.1

**Comment by qingzhuozhen** [comment]
Hi @junjie, thanks for bring this up. Actually this is intentional in our Identify class. Inside one identify, there could be multiple ways to handle user properties, set, unset, add, remove, etc. For this reason, inside one identify object, we are preventing the same property updating again and show up in various operations to prevent confusion. I would suggest when update, each time just use a new Identify object instead of the same one.

**Comment by junjie** [comment]
I see. I've come to realise that after studying the code, thanks for the clarification @qingzhuozhen

I think on re-reading the documentation, it is saying that it will overwrite the value of the property on Amplitude's server, and not in the Identify object.
