### ISSUE TITLE
### Summary

### ISSUE THREAD

**Issue by jcarltonj** [amplitude/Amplitude-iOS#390]
### Summary

Any timeline on when this will be merged? PR has been open for 2 months and now it's approved. Would love this feature.

 Adds support on Swift Package Manager for WatchOS
Fixes https://github.com/amplitude/Amplitude-iOS/issues/370

### Checklist

* [X] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-iOS/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change? No

__Originally posted by @4brunu in https://github.com/amplitude/Amplitude-iOS/pull/381__

**Comment by bohan-amplitude** [comment]
Hi @jcarltonj ,

Just merged the PR. Thank you.

**Comment by bohan-amplitude** [comment]
I'm working on bump the version but github actions for release seems need some upgrade. Will be done ASAP.

**Comment by jcarltonj** [comment]
Got it, we've been having those issues too. This is the link for early access if you're trying to get on macOS 12. https://forms.gle/D1ihWjw3xDfjYbu67 and here is the issue if you haven't seen it yet https://github.com/actions/virtual-environments/issues/3649

**Comment by bohan-amplitude** [comment]
Version bumped. Please check out version 8.9.0
