### ISSUE TITLE
Unable to build project with code coverage that depends on Amplitude

### ISSUE THREAD

**Issue by lalunamel** [amplitude/Amplitude-iOS#397]
When building our iOS project at Gusto, I've found that it fails when code coverage is enabled. Specifically, linking the Amplitude-iOS library fails with 

```
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in Amplitude.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've found the solution to this error, but it requires adding a linker flag (`-fprofile-instr-generate`) to your `Package.swift`. I would have liked it much better if the fix only required changes to our local repo!

Unfortunately I'm not able to reproduce this bug on a small sample repo. I also can't give you access to Gusto's code to check out what's going on. Happy to provide build logs though!

If you're concerned that this change will negatively impact other users of your library, I totally understand. According to the documentation for this flag, though, `linking together code with and without coverage instrumentation is supported. Uninstrumented code simply won’t be accounted for in reports.` - so no impact expected on users that don't have code coverage enabled.

You can see more technical information in the PR I've created: https://github.com/amplitude/Amplitude-iOS/pull/398

Metadata:
MacOS 12.3.1 (21E258)
XCode 13.3.1 (13E500a)
This issue appears for all versions of Amplitude-iOS
I'm building for an iOS app

**Comment by yuhao900914** [comment]
Closed this issue since the fix has been merged. https://github.com/amplitude/Amplitude-iOS/pull/398
@lalunamel Thanks for your contribution to Amplitude-iOS!
