### ISSUE TITLE
Tracking wrong carrier

### ISSUE THREAD

**Issue by bguidolim** [amplitude/Amplitude-iOS#399]
## Expected Behavior
A valid carrier should be tracked.

## Current Behavior
Getting the wrong carrier using a deprecated API

## Steps to reproduce:
1. Have a physical SIM card and an e-SIM configured in an iPhone
2. Disable one of the lines
3. It's possible that Amplitude gets the disabled carrier

## Possible Solution

Consider this getter: https://github.com/amplitude/Amplitude-iOS/blob/55ee555c68c4c8e36d1166b608447cab3aec6b4f/Sources/Amplitude/AMPDeviceInfo.m#L103-L125

- It's using a deprecated API (from iOS 12) to get the carrier name `subscriberCellularProvider`. This method was used before iPhone became dual-sim
- A condition should be done to use the new property `serviceSubscriberCellularProviders`, which is a Dictionary
- A carrier may be inactive, then the best approach to a single carrier is checking the values of the Dictionary, which can have 2 keys with one or more `nil` values
- Currently, this property is working like a lazy property, this doesn't seem right since the carrier can change. The best approach would be to implement the [notifier block](https://developer.apple.com/documentation/coretelephony/cttelephonynetworkinfo/3024512-servicesubscribercellularprovide?language=objc) or remove the initial check and keep a strong reference of `CTTelephonyNetworkInfo`

The solution in Swift can be found here: https://github.com/marmelroy/PhoneNumberKit/blob/5a1ff64be62f7ddea35618e6084997419a3f03d2/PhoneNumberKit/PhoneNumberKit.swift#L303-L307

I would open a PR fixing this issue but seems the code base heavily relies on Obj-C runtime and I don't want to break anything (and too lazy to re-learn stuff 🤣).

**Comment by haoliu-amp** [comment]
Thanks for reporting it! We will prioritize it soon.

**Comment by liuyang1520** [comment]
Thanks for reporting this! Based on my investigation, I have opened a PR (#400) for fixing this issue. I have tested it on a iPhone 13 mini with only one SIM. However, I don't have a iOS device with 2 SIMs, @bguidolim could you please help to test this?

**Comment by bguidolim** [comment]
@liuyang1520 tested and working well. I've just pointed out an improvement on your PR to avoid flooding the console with warnings.
Maybe for a future improvement, on the product level, make Amplitude support an array of carriers instead of a single one.
Thx for fix.

**Comment by liuyang1520** [comment]
Thank you @bguidolim for testing and reviewing my PR, an update is pushed based on your suggestion.
For the future improvement to make Amplitude support multiple carriers, I will discuss with team about it, to see what/when we can provide to support.
Thanks for supporting Amplitude!

**Comment by liuyang1520** [comment]
@bguidolim , the fix for this is merged and released, thanks again for your help!
For the future improvement, in order to support dual SIM device (iOS here, [Android](https://github.com/amplitude/Amplitude-Android/blob/main/src/main/java/com/amplitude/api/DeviceInfo.java#L116)) without breaking backwards-compatibility, I was thinking:
1. string concat (might break search/index)
2. add extra attribute like `Carrier2` (empty for single SIM device)
3. array attribute for `Carrier` (need to investigate more on this)

I brought this to team and created an internal feature ticket to track. Would like to learn any suggestion/proposal from you on this, what kind of solution are you looking for?

**Comment by bguidolim** [comment]
I'm not sure how important is to track all the carriers, the fix provided on your PR gets the most of cases tracking the "main" carrier, which would be enough for my use case at least.

Considering the abovementioned options, I would go for option 2 or 3. However, I don't know if there are devices with more than 2 carriers or if they would be something in the near future. So, the easiest way would be option 2, but the safest way would be option 3.

**Comment by liuyang1520** [comment]
Got it, thanks @bguidolim for your feedback! In this case, this potential future change sounds like a low-priority feature. I will close this issue. We will watch for more feedback/concerns in this and Android repo to see when/what we can do for better supporting the devices with two carriers (FYI @haoliu-amp).
