### ISSUE TITLE
Amplitude will not build as a Swift Package in Xcode

### ISSUE THREAD

**Issue by pmurphyjam** [amplitude/Amplitude-iOS#401]
## Expected Behavior
Should build
## Current Behavior
Showing Recent Messages
The package product 'Amplitude' cannot be used as a dependency of this target because it uses unsafe build flags.

## Possible Solution
Use prior version

## Steps to Reproduce
Just try to build it as a Swift Package

## Environment
- SDK Version: Latest 8.10.1
- Device: iPhone 13, 2020 MacBook Pro 16-inch 
- OS Version: . iOS 15.4, MacOS 12.4

**Comment by roimulia2** [comment]
Same issue here. Please fix it ASAP we want to submit new version to the store.

**Comment by vvbutko** [comment]
Same issue:
> The package product 'Amplitude' cannot be used as a dependency of this target because it uses unsafe build flags.

**Comment by larryonoff** [comment]
Same issue. 8.10.0 works for me.

**Comment by LaurentiuUngur** [comment]
Same here

**Comment by roryprior** [comment]
Also having this issue, specifying 8.10.0 for now works but hope this can be resolved and avoided in future.

**Comment by lewis-smith** [comment]
I also see this issue

**Comment by georgbachmann** [comment]
Same here

**Comment by BastienPenalba** [comment]
Same here ☹️

**Comment by liuyang1520** [comment]
Thanks for reporting this! We have reverted the `unsafeFlags` change and published a new version `v8.10.2`.
