### ISSUE TITLE
UpperCased Boolean Value

### ISSUE THREAD

**Issue by FranckLetellier** [amplitude/Amplitude-iOS#415]
## Expected Behavior
We are sending bool value to the SDK. On the dashboard, we are getting lower cased `true` or `false` value

## Current Behavior
We are getting Upper cased `True` and `False` value more recently. 

## Possible Solution
Could it be related to iOS 16 ? The change started around august/september 2022

<img width="1647" alt="Screenshot 2022-10-19 at 17 10 00" src="https://user-images.githubusercontent.com/8386042/196731441-d951fddd-5d1f-4c75-84d4-dd742101a1fd.png">

<img width="1646" alt="Screenshot 2022-10-19 at 17 12 34" src="https://user-images.githubusercontent.com/8386042/196731654-d81c7ffa-6318-49b3-885e-47669714e772.png">

## Steps to Reproduce
Here is the piece of code that we user (simplified) 
```swift
 private static func setAmplitudeUserProperty(_ value: Any?, for key: String) {
            Amplitude.instance().setUserProperties([key: value])
    }
```
And we are using it this way 
```swift
setAmplitudeUserProperty(true, "Pro") 
```

## Environment
- SDK Version: 8.14.0
- Device: Any device
- OS Version: Seems to happen more on iOS 16, but might be unrelated

**Comment by kevinpagtakhan** [comment]
Hi @FranckLetellier, thank you for choosing Amplitude. We'll look into this issue further. Any chance you can share the link to your dashboard?

**Comment by FranckLetellier** [comment]
Hi @kevinpagtakhan , I can ask, but I don't think we are allowed to share it.

**Comment by FranckLetellier** [comment]
Actually this is okay @kevinpagtakhan, here[ is the link](https://analytics.amplitude.com/photoroom/chart/n5y6jci?source=redirect%3A%20chart%20saved?source=copy+url)

**Comment by justin-fiedler** [comment]
Hi @FranckLetellier wanted to follow up on this and let you know this is outside of the SDK. If this is still an issue for you can you please submit an issue to our support team to help investigate https://support.amplitude.com
