### ISSUE TITLE
API call with unopened database connection pointer

### ISSUE THREAD

**Issue by SlavianaKaziuko** [amplitude/Amplitude-iOS#419]
Can smbd please suggest on the issue

## Current Behavior
Constantly getting warnings
[logging] API call with unopened database connection pointer
[logging] misuse at line 136892 of [bc8a7f24e4]

## Steps to Reproduce
Amplitude.instance().initializeApiKey(key)
And nothing more

## Environment
- SDK Version: 4.9.3
- Device:  iPhone 13, 2021 MacBook Pro 16-inch
- OS Version: iOS 16.0, MacOS 12.6

**Comment by bohan-amplitude** [comment]
Hi @SlavianaKaziuko,

Thank you for the feedback. Could you try the last version 8.14.0 SDK and test? We are fixing bugs and improve features for SDK during version release. Please let me know if you need help upgrade SDK version.
