### ISSUE TITLE
Crash in 3.1.0

### ISSUE THREAD

**Issue by josipbernat** [amplitude/Amplitude-iOS#42]
I was using Cocoapods version 3.0.0 and after upgrading to 3.1.0 I'm getting infinite loop and EXC_BAD_ACCESS in the end.
Take a look at attached screenshot for more details. It doesn't happen in Simulator but on real device. I've tested using iPhone 5C / iOS 9.0.2

<img width="1440" alt="screen shot 2015-10-06 at 17 22 02" src="https://cloud.githubusercontent.com/assets/2537227/10313280/2f66afea-6c4f-11e5-85a4-aaa33cf8002a.png">

**Comment by djih** [comment]
Hi,

Thank you for bringing this to our attention. Are you seeing this error consistently? In the debugger can you see if there is a value assigned to BACKGROUND_QUEUE_NAME? I'm trying to figure out what that EXC_BAD_ACCESS address is pointing to.

**Comment by djih** [comment]
Hi,

We rereleased v3.1.0. You should be able to pull the latest version with pod install. You might need to clear your Cocoapods cache.
