### ISSUE TITLE
No HTTPS for https://developers.amplitude.com/docs/ios

### ISSUE THREAD

**Issue by tonyatoms** [amplitude/Amplitude-iOS#422]
## Expected Behavior
I expect to be able to securely open https://developers.amplitude.com/docs/ios

## Current Behavior
When I try open the above URL I get:
```
This site can’t provide a secure connectiondevelopers.amplitude.com sent an invalid response.
ERR_SSL_PROTOCOL_ERRO
```

## Possible Solution
Look into the HTTPS configuration? Is there a valid certificate?

## Steps to Reproduce

1. Try to open [the above URL I get](https://developers.amplitude.com/docs/ios) with a web browser.

## Environment
- SDK Version: n/a
- Device:  Seeing the error in in multiple browsers (Brave and Chrome)
- OS Version: n/a

**Comment by kevinpagtakhan** [comment]
Hi @tonyatoms, the link above is for our old dev docs and is in the process of deprecation. We had redirects setup but is currently down. We are in currently trying to restore this. In the meantime, here's the direct link to our new docs: https://www.docs.developers.amplitude.com/data/sdks/ios/. Thank you for your patience.
