### ISSUE TITLE
Amplitude_iOS normal (in target 'Amplitude-iOS' from project 'Pods')

### ISSUE THREAD

**Issue by gozegotushar** [amplitude/Amplitude-iOS#438]
## Expected Behavior

ios build getting failed

** ARCHIVE FAILED **
The following build commands failed: Ld /Users/deploy/Library/Developer/Xcode/DerivedData/ResidentApp-bypmldyymykjubaaohhggejsdccs/Build/Intermediates.noindex/ArchiveIntermediates/ResidentApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude_iOS.framework/Amplitude_iOS normal (in target 'Amplitude-iOS' from project 'Pods')

## Current Behavior
'
ios build getting failed

## Steps to Reproduce
 

1.
2.
3.
4.

## Environment
- SDK Version: : v4.10
- Device: iPhone 13, 2020 MacBook Pro 145-inch
- OS Version:  iOS 16, MacOS 12.1

**Comment by justin-fiedler** [comment]
Hi @gozegotushar, [v4.10](https://github.com/amplitude/Amplitude-iOS/releases/tag/v4.10.0) is very old (over 3 years out of date).

Can you please update to the latest version [8.16.0](https://github.com/amplitude/Amplitude-iOS/releases/tag/v8.16.0) and try again. Thank you.

I also noticed a change in Cocoapods starting version [5.0.0](https://github.com/amplitude/Amplitude-iOS/releases/tag/v5.0.0) that maybe be relevant.
