### ISSUE TITLE
Vulnerability: App is Encoding Sensitive Information Using Outdated or Insecure Cryptography

### ISSUE THREAD

**Issue by aryanamex** [amplitude/Amplitude-iOS#439]
Vulnerability: App is Encoding Sensitive Information Using Outdated or Insecure Cryptography

Description
The application was found to operate weak cryptographic algorithms on sensitive data while exercising the app. These outdated algorithms are often in violation of common compliance standards and can be vulnerable to publicly-disclosed and non-public attacks. The sensitive data being encoded with the weak algorithm is also at a greater risk of being exposed due to the often trivial effort to decode the data.

Inspect the app's source code to identify instances of cryptographic algorithms that are known to be weak, such as:
• [DES, 3DES](https://www.enisa.europa.eu/publications/algorithms-key-size-and-parameters-report-2014)
• RC2
• RC4
• [BLOWFISH](https://www.enisa.europa.eu/publications/algorithms-key-size-and-parameters-report-2014)
• MD4
• MD5
• SHA1

**Comment by justin-fiedler** [comment]
Thank you @aryanamex for bring this to our attention. We have added this to our backlog. I will keep you updated on our progress.
