### ISSUE TITLE
How to integrate Amplitude into a single-target Apple Watch app?

### ISSUE THREAD

**Issue by LukasCZ** [amplitude/Amplitude-iOS#440]
## Summary

I'd like to start using Amplitude in my watchOS app. I have recently migrated my Xcode project structure to use the new single-target setup (the watch app is just one target in Xcode, as opposed to two).

I have a few questions:
1) How do I make it work? I have followed the guide at [https://www.docs.developers.amplitude.com/data/sdks/ios/](https://www.docs.developers.amplitude.com/data/sdks/ios/) but I don't see any events being recorder in my charts.
2) How do I differentiate between my iOS and watchOS users? Should I be using the same API key for both? And if yes - is it possible to somehow split the analytics in Amplitude dashboard between iOS and watchOS users?

Thanks a lot for answering these! -Lukas

**Comment by Mercy811** [comment]
Hi @LukasCZ, 

>1. How do I make it work? I have followed the guide at https://www.docs.developers.amplitude.com/data/sdks/ios/ but I don't see any events being recorder in my charts.
- Looks like you are in EU, did you configured the [SDK to EU data residency](https://www.docs.developers.amplitude.com/data/sdks/ios/#eu-data-residency)
- Did you see any error from [debug logging](https://www.docs.developers.amplitude.com/data/sdks/ios/#debug-logging)?
- Did you use the right events to create the chart ? Could you see if events are in [Ingestion Debugger](https://www.docs.developers.amplitude.com/data/debugger/#ingestion-debugger) or [User Lookup](https://www.docs.developers.amplitude.com/data/debugger/#user-lookup)

> 2. How do I differentiate between my iOS and watchOS users? Should I be using the same API key for both? And if yes - is it possible to somehow split the analytics in Amplitude dashboard between iOS and watchOS users?
You should be able to differentiate them by `user properties` -> `device type`. The `device type` is handled by Amplitude, so no extra work to do and you can use the same API key.

**Comment by LukasCZ** [comment]
Hi @Mercy811 ,

thank you. I have looked again through the dashboard and was able to find that events from Apple Watches are being reported since I did a release 4 days ago.

Regarding using the EU server zone: I have added the:
`[[Amplitude instance] setServerZone:EU];`

Do I need to change something in my Amplitude account as well? I was trying to find in Settings in which zone is my account created but I couldn't find it.

And as for differentiating between devices - is there an easier way? Can I apply that somehow on an entire dashboard? Also - I have some events that are reported on both iOS and watchOS, but they have different parameters - how do these get merged?

**Comment by Mercy811** [comment]
Hi @LukasCZ,

If you were able to ingest event, keep the Amplitude application settings (stay in EU zone) and use the same API key, then it should not be not the case of EU residency. So you don't need to do anything in your Amplitude account. 

> I have recently migrated my Xcode project structure to use the new single-target setup

Sounds like the Amplitude SDK stops working after your migration to the new Xocde project structure. Did you do any testing to confirm that the SDK still works after the migration? 

> And as for differentiating between devices - is there an easier way? Can I apply that somehow on an entire dashboard? Also - I have some events that are reported on both iOS and watchOS, but they have different parameters - how do these get merged?

I believe the way I recommend is the easiest way to distinguish them. To clarify, you don't need to do any extra work. When creating a chart, for example, you can just simply
- choose the device type you want
- group by device type 
![image](https://github.com/amplitude/Amplitude-iOS/assets/31029607/bfe52826-1761-4106-89fe-1705e325669d)
