### ISSUE TITLE
Installation instructions are broken in website

### ISSUE THREAD

**Issue by sergiocampama** [amplitude/Amplitude-iOS#446]
![Screenshot 2023-06-12 at 1 56 22 PM](https://github.com/amplitude/Amplitude-iOS/assets/689198/d17ed027-3edd-4216-b234-0219b30aa072)

This is what appears in the developer portal, it should say "Amplitude" and not "Amplitude-iOS, took me some time to figure out you had renamed the pod without deprecating the old one

**Comment by yuhao900914** [comment]
hI @sergiocampama, thanks for choosing amplitude. 
Can you share the link to where you see this wrong instruction? 
Here is [our developer doc](https://www.docs.developers.amplitude.com/data/sdks/sdk-quickstart/#install-the-dependency_3), it's using the correct library name.

**Comment by yuhao900914** [comment]
The pr for fixing the wrong instruction has been merged, it will be live soon. We also have a plan to deprecate the legacy SDK. 
Closing this pr since the instruction has been fixed.
