### ISSUE TITLE
Pod update/install fails - Could not find remote branch v3.1.0 to clone

### ISSUE THREAD

**Issue by coolnalu** [amplitude/Amplitude-iOS#45]
[!] Error installing Amplitude-iOS
[!] /usr/bin/git clone https://github.com/amplitude/Amplitude-iOS.git /var/folders/sq/86hhftz177scgdzggq3zgf1h0000gn/T/d20151006-14311-4mjtwk --single-branch --depth 1 --branch v3.1.0

Cloning into '/var/folders/sq/86hhftz177scgdzggq3zgf1h0000gn/T/d20151006-14311-4mjtwk'...
warning: Could not find remote branch v3.1.0 to clone.
fatal: Remote branch v3.1.0 not found in upstream origin

pod --version
0.39.0.rc.1

**Comment by djih** [comment]
Hi,

We took down v3.1.0 temporarily to patch a bug: https://github.com/amplitude/Amplitude-iOS/releases/tag/untagged-2cf3122cbf1ce3b2ece3. Will update you when it is rereleased.

**Comment by djih** [comment]
Hi,

We rereleased v3.1.0. You should be able to do pod install now. You also may need to clear your Cocoapods cache.
