### ISSUE TITLE
Feature Request: Add a way to be notified when the session id changes

### ISSUE THREAD

**Issue by jboulter11** [amplitude/Amplitude-iOS#454]
## Summary
While there is a very helpful method to get the session id from Amplitude, there is no way to be notified of when it changes.  We'd like some way of knowing when the session changes so we can log our own session start events as well as so we can expose a lightweight way of being notified about the changes that do not require linking to the Amplitude SDK directly.

Two example ways of doing this might be:
1. A public delegate protocol we can adopt to be directly notified about session changes.
```swift
protocol AmplitudeSessionIdNotificationDelegate {
    func sessionIdDidChange(oldSessionId: Int64, newSessionId: Int64)
}
```
2. An NSNotificationCenter notification we could observe with a frozen (never changing ever) notification name.

I'd specifically like to be notified when the ID changes.  I'd expect that the method would be called on every new app boot as well as any time the session id changes when the app's still stood up (not terminated).  My names above are only suggestions, obviously feel free to name it what you think makes the most sense.

## Motivations
At Dropbox, we're in the process of re-working a lot of our analytics logging.  One thing that's missing is that we don't have a good app-wide session ID, we only have what get logged by Amplitude (to which only a subset of our logs are passed).  We would like to adopt the Amplitude SDK's session id as our app-wide session id.

In order to do this, we'd want to also attach it to our legacy events and events that might go to other destinations besides where Amplitude sends events, as well as logging our own session start/end events with custom information and naming.  The feature would allow us to log those custom session start/end events as well as more easily expose the session id via `rx`-style observables to other parts of the app without needing to link to the Amplitude SDK.

Lastly, this would be something we'd also want on Android's SDK.

Please let me know how amenable this is and whether it can be done.  Thank you!

**Comment by Mercy811** [comment]
HI @jboulter11, thanks for providing such detailed description and potential solutions. Can I know why you want to log your own session start events as the SDK supports out-of-box session tracking? 

Also a heads up here that we are planning to GA [Swift SDK](https://github.com/amplitude/Amplitude-Swift) next quarter and put iOS SDK to end-of-support status according to the [maintenance and support policy](https://www.docs.developers.amplitude.com/data/sdks/sdk-maintenance-and-support/). We will put this into our backlog, but regarding to our deprecation plan, unless it's blocking data ingestion, it has a limited chance to be put into our roadmap unfortunately.

**Comment by justin-fiedler** [comment]
Hi @jboulter11, you can hook into the event stream using Middleware. Middleware is called for each event, including session events. If you set `trackingSessionEvents = YES` then add a custom middleware to handle the `session_start` event. Hope this helps!

Documentation here:
* Middleware - https://www.docs.developers.amplitude.com/data/sdk-middleware/
* Enable session events - https://www.docs.developers.amplitude.com/data/sdks/ios/#user-sessions
* Middleware example (ObjC) - https://github.com/amplitude/Amplitude-iOS/blob/main/Tests/AmplitudeTests.m#L1227-L1247C1
