### ISSUE TITLE
Not run in simulator 

### ISSUE THREAD

**Issue by ravipappyogi** [amplitude/Amplitude-iOS#457]
When trying to run the application with Amplitude get the below error 
Undefined symbol: _OBJC_CLASS_$_Amplitude

## Expected Behavior
Should be run with the simulator

## Current Behavior
Not able to run with the simulator 

## Possible Solution
The simulator getting fail but in iPhone device run properly.

## Steps to Reproduce
1. Added swift package library 
2. Application run 
3. Fail 

## Environment
- SDK Version: Swift Package manager Amplitude version 8.16.4
- Device: iPhone simulator 
- OS Version: macOS 13.4 (M1), Xcode version 14.2

 
Please help us to handle this error and make a runnable build on the iOS simulator.

**Comment by Mercy811** [comment]
Hi @ravipappyogi, it looks like that the linker is unable to find the definition of the Amplitude class in Objective-C. Could you check if you've followed the guides to [install the dependency](https://www.docs.developers.amplitude.com/data/sdks/sdk-quickstart/#install-the-dependency_3)?

**Comment by ravipappyogi** [comment]
Hello 
I have followed this step to add Amplitude 
1. Navigate to File > Swift Package Manager > Add Package Dependency.
2. Enter https://github.com/amplitude/Amplitude-iOS into the search bar.
3. It automatically resolves to the latest version.

Also, not showing any error while I connected the iPhone device and run on that. Only getting a fail while I am trying to run in the simulator.

Undefined symbol: OBJC_CLASS$_Amplitude

Please let us know if anything manually adds any dependency or if any linker flag needs to add to build settings.

**Comment by yuhao900914** [comment]
@ravipappyogi 
That's all you need to install amplitude. I'm not able to reproduce this in my local. There have several things you can check.
- Can clean build and rebuild to see if it fixes the issue?
    -  Xcode -> Product -> Clean Build Folder and then build again.
-  Please check after you installed Amplitude-iOS SDK, if there are 2 packages has been installed.
    <img width="275" alt="Screen Shot 2023-07-10 at 4 23 42 PM" src="https://github.com/amplitude/Amplitude-iOS/assets/13028329/e48f5612-2306-4fab-acd5-0ea41d44655b">
    Check if the `Amplitude` Framework has been auto-added into frameworks section.
    <img width="865" alt="Screen Shot 2023-07-10 at 4 24 53 PM" src="https://github.com/amplitude/Amplitude-iOS/assets/13028329/738ceacd-1efc-49c9-8607-b1f2199cd428">
    Check if `Amplitude` is under `Link Binary With Libraries` for your selected target.
    <img width="874" alt="Screen Shot 2023-07-10 at 4 33 03 PM" src="https://github.com/amplitude/Amplitude-iOS/assets/13028329/bda03cf8-ea54-459d-bcaf-47006d4259da">

- Please also try to clone [this simple example ](https://github.com/yuhao900914/AmplitudeLegacyiOSSDKTestSwiftApp) to see if it can be built successfully.

Thanks.

**Comment by yuhao900914** [comment]
Hi @ravipappyogi ,
any progress on this issue?

**Comment by ravipappyogi** [comment]
Hello @yuhao900914 
Yes solved the simulator run issue with following changes 

Build Settings > Build Active Architecture Only > DEBUG = Yes

Thanks
