### ISSUE TITLE
Is it possible to build static_xcframework from source code?

### ISSUE THREAD

**Issue by outsourcestudio** [amplitude/Amplitude-iOS#458]
Hi!

I need static_xcframework to integrate Amplitude in the project.
Like Firebase provides https://github.com/firebase/firebase-ios-sdk/releases/tag/10.13.0 zip file Firebase.zip

There is just source code
https://github.com/amplitude/Amplitude-iOS/releases
Is it possible to build static_xcframework from source code?

Thank you!

**Comment by yuhao900914** [comment]
Thanks for choosing amplitude. Our team is looking into this. 
Currently, we do not support static_xcframework.
