### ISSUE TITLE
How can I disable tracking in Swift?

### ISSUE THREAD

**Issue by wlxo0401** [amplitude/Amplitude-iOS#459]
## Summary
![스크린샷 2023-08-04 오후 7 10 28](https://github.com/amplitude/Amplitude-iOS/assets/57979066/0bc2d82a-676f-49b1-bf01-31b3acd875c7)

My project is Swif.

However, only Objective-C is available for how to use Disable tracking.

How can I apply it in Swift as well?? Or are there any related documents?

The code I want to do with Swift is below.

#import "AMPTrackingOptions.h"
        
AMPTrackingOptions *options = [[[[AMPTrackingOptions options] disableLatLng];
[[Amplitude instance] setTrackingOptions:options];

**Comment by yuhao900914** [comment]
Hi @wlxo0401,
Thanks for using amplitude. I added the swift example in the doc. It will be merged and released soon. 
Also sharing the snippet here. 
```
            let trackingOptions = AMPTrackingOptions().disableCity().disableCarrier();
            Amplitude.instance().setTrackingOptions(trackingOptions!);
```
Closing this issue. Feel free to reopen this if you still have issues.
Thanks.

**Comment by yuhao900914** [comment]
Just want to share with you. We have a new iOS SDK which is developed using swift. It will be GA soon. And this is the SDK we are going to deprecate. [Read more](https://www.docs.developers.amplitude.com/data/sdks/sdk-maintenance-and-support/#sdk-major-version-life-cycle). 
There has been a lot of improvement in the latest iOS SDK. Please take a look at [here](https://www.docs.developers.amplitude.com/data/sdks/ios-swift/). [ More information](https://www.docs.developers.amplitude.com/data/sdks/sdk-architecture/) related to the latest architecture.
