### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by alec-c4** [amplitude/Amplitude-iOS#46]
Hi,
could you please add support for Carthage? You just need to add shared framework scheme

**Comment by lewisskslipstone** [comment]
Please do this.  Cocoa pods are so invasive I hate to use it.

**Comment by djih** [comment]
We will take a look into Carthage

**Comment by djih** [comment]
@alec-c4 can you elaborate? Under Manage Schemes, I see that our Amplitude and AmplitudeTests schemes are already shared. Is that what generates this? https://github.com/amplitude/Amplitude-iOS/tree/master/Amplitude.xcodeproj/xcshareddata/xcschemes

**Comment by alec-c4** [comment]
@djih sure. I'm planing to push something soon :)

**Comment by mpurland** [comment]
@djih The target is a static library, not a framework.

**Comment by ILI4S** [comment]
carthage support would be great

**Comment by lewissk** [comment]
is there still no carthage support?

**Comment by djih** [comment]
Carthage support added in v3.8.4.

Instructions:
If you are using Carthage, add the following line to your Cartfile: `github "amplitude/Amplitude-iOS"`. Just add `#import "AmplitudeFramework/Amplitude.h"` to import all of the Amplitude header files.

**Comment by djih** [comment]
Just a quick update for people following this thread, @lexrus was able to rename the framework so that instead of `AmplitudeFramework`, you do `#import "Amplitude/Amplitude.h" instead. We re-released v3.8.4 yesterday. Just do a `carthage update` to pull the change.
