### ISSUE TITLE
Xcode 15 and MacOS Sonoma throw analyze error

### ISSUE THREAD

**Issue by jostster** [amplitude/Amplitude-iOS#462]
Xcode Cloud analyze feature throws and error about nil being returned from non nil which breaks the build process if you have an Analyze workflow.

## Expected Behavior
Analyze error is not thrown

## Current Behavior
Analyze error is thrown

## Possible Solution
Exclude from analyze or fix the 

## Steps to Reproduce
 

1. Run Xcode Analyze on a project that uses amplitude-ios
2.
3.
4.

## Environment
- SDK Version: 8.17.1
- Device: 
- OS Version: Xcode 15 RC, MacOS Sonoma RC

<img width="891" alt="image" src="https://github.com/amplitude/Amplitude-iOS/assets/278510/7bc6abc6-3aa6-4fdd-9fe2-0bc196391104">
<img width="409" alt="image" src="https://github.com/amplitude/Amplitude-iOS/assets/278510/318d470f-4dee-404a-9c65-5c38487be7e0">

**Comment by yuhao900914** [comment]
@jostster  Please check the latest version for the fix. Please re-open this ticket if there is still an issue. 
Thanks.
