### ISSUE TITLE
Apple says that support for the iad framework has ended and the framework must be removed.

### ISSUE THREAD

**Issue by colondeethpark** [amplitude/Amplitude-iOS#467]
## Summary

Apple says that support for the iad framework has ended and the framework must be removed.
Are you using iad framework for amplitude sdk?
If you are using it, what are your plans for removal?
https://developer.apple.com/documentation/iad
![스크린샷 2023-10-19 오후 12 45 15](https://github.com/amplitude/Amplitude-iOS/assets/49852322/8bf3b780-441a-4944-93b6-7a5bacea2529)

**Comment by Mercy811** [comment]
Hi @colondeethpark, thanks for choosing Amplitude and keeping us up with the latest news from Apple. iAd is used for attributing downloads from Apple Search Ads campaigns while Amplitude SDKs let you send events to Amplitude. I confirm that we don't use iAd framework.
