### ISSUE TITLE
Privacy Manifests

### ISSUE THREAD

**Issue by wlxo0401** [amplitude/Amplitude-iOS#470]
I think we need Privacy Manifests due to Apple policy.

Is there no problem with the contents below?

Read [Apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc), which say:
----
From Fall 2023 you’ll receive an email from Apple if you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file. From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

**Comment by choulepoka** [comment]
+1 on this, Apple is putting pressure on us to provide privacy manifest, this should get done ASAP.

**Comment by wlxo0401** [comment]
@yuhao900914 
Any support/plan of Privacy Manifest?

**Comment by izaaz** [comment]
Thank you for reaching out. We are in the process of adding this to our SDK and will update this thread soon.

**Comment by wlxo0401** [comment]
@izaaz 

Thank you for your response.

**Comment by wlxo0401** [comment]
I discovered a new fact while testing. Until now, most of the libraries that have added PrivacyInfo have not been marked in PrivacyReport. 

However, when an item is added to the 'Personal Information Nutrition Label Type', the library name is displayed in the personal information protection report. 

Many libraries have updated PrivacyInfo without adding anything from Privacy Nutrition Label Types.

Does anyone know about this? Is "Privacy Nutrition Label Types" a must-have item?

Please feel free to leave your opinion.

**Comment by wlxo0401** [comment]
https://github.com/amplitude/Amplitude-iOS/issues/482

**Comment by iharkatkavets** [comment]
Added in [v8.18.0](https://github.com/amplitude/Amplitude-iOS/releases/tag/v8.18.0)

**Comment by wlxo0401** [comment]
@iharkatkavets I don't think it's finished perfectly.

**Comment by sdurban** [comment]
I have made a PR to fix the issue with the privacy manifest so that it works from both SPM and Cocoapods.

The issue was that the file was not being copied into the SPM and Cocoapods package.

https://github.com/amplitude/Amplitude-iOS/pull/487

![image](https://github.com/amplitude/Amplitude-iOS/assets/4395258/5d96dc99-7ac0-4d09-9c6a-cdfda7583ccd)

**Comment by georgbachmann** [comment]
A quick question about the topic of privacy manifests. There is also the option to define `Privacy Tracking Domains`. Do I need to add amplitude there, if we only use Amplitude for usage tracking of your app but DO NOT link user-information? So we do not set user-ids what-so-ever. We just need it to get an understanding of how users interact with our app.
