### ISSUE TITLE
Why does `-[Amplitude getDeviceId]` sometimes return empty string?

### ISSUE THREAD

**Issue by macdrevx** [amplitude/Amplitude-iOS#485]
## Summary

We're using v8.17.1, and we've noticed that sometimes `-[Amplitude getDeviceId]` returns an empty string. This seems to correlate with some other errors related to the device being out of disk space. Does it make sense that a no-disk-space-left situation would cause `-[Amplitude getDeviceId]` to return an empty string?

**Comment by crleona** [comment]
Hi @macdrevx - `getDeviceId` should always return a value as of version 8.19.1.
