### ISSUE TITLE
`initializeApiKey` deprecated?

### ISSUE THREAD

**Issue by tonyxiao** [amplitude/Amplitude-iOS#49]
https://github.com/amplitude/Amplitude-iOS/blob/master/Amplitude/Amplitude.h#L270-L272

I thought that's the recommended way to initialize Amplitude. Why is it deprecated?

**Comment by djih** [comment]
Calling methods directly on Amplitude is deprecated. You should instead call it on the instance:  `[[Amplitude instance] initializeApiKey:@"YOUR_API_KEY_HERE"];`

The readme explains this in the Setup section

**Comment by tonyxiao** [comment]
Ah I see. Thanks!
