### ISSUE TITLE
Int and Decimal event properties missing from events

### ISSUE THREAD

**Issue by initishbhatt** [amplitude/Amplitude-iOS#496]
## Expected Behavior
The expected behavior is that all event properties, including integers and decimals such as amount and id, should be visible and available in the Amplitude dashboard for analysis. All properties should be correctly captured and displayed alongside other string properties like name and email.

## Current Behavior
When observing events in the Amplitude dashboard, properties that are of type integer and decimal (e.g., amount, id) are missing. Other properties like name and email are visible and recorded as expected.

## Steps to Reproduce
 

1. Open the application and navigate to the feature where the events are triggered.
2. Perform an action that triggers the event, such as tapping a button which sends event properties including amount, id, name, and email.
3. Review the event in the Amplitude dashboard.
4. Observe that while string properties such as name and email are recorded and visible, integer and decimal properties like amount and id are missing from the event details in the dashboard.

## Environment
- SDK Version:  1.3.3
- Device:  iPhone 15Pro
- OS Version:  iOS 17.4

**Comment by crleona** [comment]
Hi @initishbhatt, I'm assuming you're using the [Amplitude-Swift](https://github.com/amplitude/Amplitude-Swift) SDK based on the version number (Please let me know if this is not the case!), and I'm unable to reproduce the issue with standard ints/floats or ints/floats wrapped in an NSNumber. Is it possible that these properties are not enabled in your tracking plan? (In Amplitude, Data-> Tracking Plan, more [details](https://help.amplitude.com/hc/en-us/articles/19717053646107-Create-a-tracking-plan))

**Comment by initishbhatt** [comment]
Hi @crleona yes we are using the Amplitude-Swift SDK and have recently migrated from the Objc SDK. The properties are enabled in the tracking plan as we use the same plan for both Android and iOS but the issue is reported only for iOS.
During debug i can see the event properties available but they are not sen on the dashboard.
```
print event.eventProperties
([String : Any?]?) 4 key/value pairs {
  [0] = {
    key = "screen_name"
    value = "test_screen"
  }
  [1] = {
    key = "id"
    value = some {
      _mantissa = (0 = 21992, 1 = 7, 2 = 0, 3 = 0, 4 = 0, 5 = 0, 6 = 0, 7 = 0)
    }
  }
  [2] = {
    key = "is_active"
    value = false
  }
  [3] = {
    key = "amount"
    value = some {
      _mantissa = (0 = 36, 1 = 0, 2 = 0, 3 = 0, 4 = 0, 5 = 0, 6 = 0, 7 = 0)
    }
  }
}
```
this is the debug print from the Amplitude SDK function where i can see the event properties id and amount but on the dashboard i can only see `is_active` and `screen_name`

```
  @discardableResult
    public func track(eventType: String, eventProperties: [String: Any]? = nil, options: EventOptions? = nil)
        -> Amplitude
    {
        let event = BaseEvent(eventType: eventType)
        event.eventProperties = eventProperties
        if let eventOptions = options {
            event.mergeEventOptions(eventOptions: eventOptions)
        }
        process(event: event)
        return self
    }
   ```

**Comment by crleona** [comment]
The `Decimal` type is not supported. Please convert it to a standard numeric value type like `Float` or `Double`, as you've described in your update.

Can I ask for your use case for the additional precision of `Decimal` over the standard types? It's unlikely that we'd be able to represent this internally at full precision even if we were to add support.

**Comment by initishbhatt** [comment]
Thanks, To be honest like so many aspects of programming, the short answer is: it depends 

i would say it was a design decision from the previous devs as the app has multiple currencies and values to deal with and Decimal makes precision easier. it only came into notice when values were missing from Amplitude.

none the less it makes a good case for us to discuss if we can adopt a Double instead of Decimal.
