### ISSUE TITLE
Amplitude Privacy Manifest Fails TestFlight Check

### ISSUE THREAD

**Issue by K2-XT** [amplitude/Amplitude-iOS#500]
## Expected Behavior
When archiving and uploading an app with Amplitude in it, TestFlight should accept it.

## Current Behavior
Apple rejects builds with Amplitude currently, because they have not declared tracking fully.
<img width="879" alt="image" src="https://github.com/user-attachments/assets/fe0d5c2a-c18d-4c27-9cec-5a4d1bfc43a4">

## Possible Solution
We've been solving this manually by adding these lines to Amplitude/Sources/PrivacyInfo.xcprivacy:
<img width="879" alt="image" src="https://github.com/user-attachments/assets/b8a161ae-b9dc-45c7-902f-8e5fb2bb63fa">

## Steps to Reproduce
1. Create an iOS app and integrate Amplitude.
2. Click "Product->Archive"
3. Click the new build, then click "Distribute App->App Store Connect->Distribute"
4. Apple will take a while to show the app. Once it does, try to release to TestFlight.
5. Apple will send the email I put in the "Current Behavior" section.

## Environment
- Device: iPhone 11, 2019 MacBook Pro
- OS Version: iOS 17.6, MacOS 14.5

**Comment by crleona** [comment]
Hi @K2-XT, please update to 8.19.2 or greater.
