### ISSUE TITLE
UI Hang Risk: Synchronous File Reading on Main Thread

### ISSUE THREAD

**Issue by ahmdmhasn** [amplitude/Amplitude-iOS#504]
## Summary
Xcode's Thread Sanitizer warns about potential UI hangs due to synchronous file reading on the main thread in `PersistentStorage.swift`. This issue is highlighted by Xcode's known hang system, which suggests migrating away from `String(contentsOf:, encoding:)`.

## Expected Behavior
No warnings should be present, and file reading operations should not risk UI hangs.

## Current Behavior
Xcode displays a warning for potential UI hangs and suggests an enhancement to the code.

### Specific Location
File: `PersistentStorage.swift`
```swift
func getEventsString(eventBlock: EventBlock) -> String? {
    ...
    content = try String(contentsOf: eventBlock, encoding: .utf8) // <-- Warning shown here
    ...
}
```

## Possible Solution
Use `url.absoluteString` instead

## Steps to Reproduce
1. Open the project in Xcode.
2. Build the project using Amplitude SDK.
3. Navigate to `PersistentStorage.swift`.
4. Locate the `getEventsString(eventBlock:)` function.
5. Observe the warning on the line using `String(contentsOf:, encoding:)`.

## Environment
- Amplitude: 1.4.5
- SDK Version: iOS 17.5
- Device: iPhone 15
- OS Version: macOS 14.5 (23F79)
- Xcode: 15.4

**Comment by crleona** [comment]
@ahmdmhasn which version of the Amplitude SDK are you using?

**Comment by ahmdmhasn** [comment]
@crleona Amplitude 1.4.5

**Comment by crleona** [comment]
@ahmdmhasn - you appear to be using an outdated version of https://github.com/amplitude/Amplitude-Swift, not https://github.com/amplitude/Amplitude-iOS. Please update.
