### ISSUE TITLE
If we want to integrate amplitude using SPM, we mostly need to use the main branch? Is it part of your roadmap to improve this?

### ISSUE THREAD

**Issue by chibombo** [amplitude/Amplitude-iOS#508]
## Summary
Xcode doesn't allow set `vx.x.x` in the version input, it requires this format `x.x.x`.

Using a branch or commit as a reference doesn't look like a good practice.

Is it part of your roadmap to improve this?

**Comment by crleona** [comment]
SPM ignores the `v` in git tags, something like `.package(url: "https://github.com/amplitude/Amplitude-iOS.git", from: "8.22.0")` should work.

**Comment by chibombo** [comment]
We discover something new every day. Thanks 🙏
