### ISSUE TITLE
Swift 2.0, XCode 7.1 Setting nil to Amplitude.instance().setUserId crashes

### ISSUE THREAD

**Issue by mbalex99** [amplitude/Amplitude-iOS#55]
Using Cocoapods 3.1.1

This happens extremely randomly... 

Commenting out the API intialization fixes everything

2015-10-18 18:10:31.352 Eden[9145:776613] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithString:]: nil argument'
*** First throw call stack:
(0x1860f82d8 0x197dcc0e4 0x1860f8218 0x186f2c824 0x10046c1b0 0x1005b3794 0x102334f94 0x10233f08c 0x1005b36c0 0x10046be30 0x10046bc20 0x100471bac 0x186fdf1c4 0x186f30604 0x186f201cc 0x186fe1f28 0x102334f94 0x10233fdb8 0x1023382c4 0x1023425d4 0x102344248 0x19862922c 0x198628ef0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by mbalex99** [comment]
This ended up going away after a clean build....

**Comment by appcelerate** [comment]
+1

**Comment by djih** [comment]
Hi @mbalex99 , you're saying if you comment out Amplitude.instance().initializeApiKey then it works? Does that mean you're trying to initialize it with a nil userId?

**Comment by djih** [comment]
@appcelerate  care to comment ^ ?

**Comment by mbalex99** [comment]
No there's a userId.

This seemed to crash 50% of the times I ran the app. However as soon as I commented out `Amplitude.instance().initializeApiKey`

The errors no longer happen.

**Comment by appcelerate** [comment]
Hi @djih,

i initialized it with 
```
[[Amplitude instance] initializeApiKey:@"...."];
```

but i will get this crash
at " dispatch_sync(_queue, ^() {" line 147 in FMDatabaseQueue.m

with this reason:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithString:]: nil argument'

**Comment by djih** [comment]
Yep, found the issue. Thanks for bringing this to our attention. It will be patched in the next release.

**Comment by djih** [comment]
https://github.com/amplitude/Amplitude-iOS/commit/bde59ab2c294710708a9aac6ed4ff7be3c45bae9 will be included in the next release

**Comment by djih** [comment]
Patch is released with v3.2.0: https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.2.0 please update your pod file
