### ISSUE TITLE
Allow user properties to be completely cleared

### ISSUE THREAD

**Issue by mquigley-ck** [amplitude/Amplitude-iOS#64]
There are many reasons that a full clear of the user properties is useful. Sometimes the user properties come from different sources (such as a server) where the keys are dynamically determined. Something like `[[Amplitude instance] clearUserProperties]`.

This would be useful in both the Android and iOS clients.

**Comment by djih** [comment]
@mquigley-ck we are adding this function to all our SDKs. It will be available in the next release. Here's the PR for the iOS SDK update: https://github.com/amplitude/Amplitude-iOS/pull/70

**Comment by mquigley-ck** [comment]
Thanks dijh!

**Comment by djih** [comment]
@mquigley-ck : clearUserProperties is now available in v3.5.0: https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.5.0. Please update your Podfile. Thank you for waiting.
