### ISSUE TITLE
Failed to get value for key opt_out from table long_store

### ISSUE THREAD

**Issue by ileitch** [amplitude/Amplitude-iOS#69]
Hey, I just upgraded to 3.4.0, and I'm now seeing in the console: `Failed to get value for key opt_out from table long_store`.

Any idea what's causing this?

**Comment by djih** [comment]
Nothing to worry about! It's just a warning because you haven't set a value for opt_out, which is okay. If it's an issue we will consider silencing it in the next release.

**Comment by ileitch** [comment]
Does opt_out not default to NO? The docs seems to suggest it should.

**Comment by ileitch** [comment]
Also, the frequency of the log line is quite high, making it a little annoying.

**Comment by djih** [comment]
I have released v3.4.1 with the logging disabled: https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.4.1. Please update and let us know if there are any more issues!
