### ISSUE TITLE
Undeclared use of identifier 'SQLITE_OPEN_READWRITE'

### ISSUE THREAD

**Issue by josipbernat** [amplitude/Amplitude-iOS#73]
I experienced this bug in version 3.2.1 when using through CocoaPods. Please check attached screenshot.
![untitled](https://cloud.githubusercontent.com/assets/2537227/12745185/5aef8046-c998-11e5-9ac3-059c45d387be.png)

**Comment by djih** [comment]
@josipbernat we removed the FMDB dependency in v2.4.0. I recommend updating to the latest version of the SDK (v3.5.0)
