### ISSUE TITLE
logRevenue and track different currencies?

### ISSUE THREAD

**Issue by aryaxt** [amplitude/Amplitude-iOS#76]
What's the proper way of tracking revenue and take different currencies into considerations? It doesn't seem like the existing methods accept the currency as a parameter

```
- (void)logRevenue:(NSString*) productIdentifier quantity:(NSInteger) quantity price:(NSNumber*) price
```

**Comment by djih** [comment]
@aryaxt unfortunately our platform cannot handle different currencies at this time (both the SDK and the dashboard). We recommend you send all of your revenue info in the same currency.

**Comment by aryaxt** [comment]
Thanks for the quick response 
:beers:

**Comment by tarun1608** [comment]
Hi @djih Is there any mechanishm available now to convert the currencies

**Comment by djih** [comment]
@tarun1608  unfortunately still no mechanism. If you have a CSM you can try submitting a feature request through them. CC @blazzy
