### ISSUE TITLE
ERROR: apiKey cannot be nil or empty, set apiKey with initializeApiKey: before calling logEvent

### ISSUE THREAD

**Issue by ileitch** [amplitude/Amplitude-iOS#93]
This error pollutes our logs for development builds because we only enable Amplitude for builds that we distribute to other people.

Is there anything we can do to silence it?

**Comment by djih** [comment]
@ileitch sorry unfortunately no way to silence it at the moment. I will add a debug flag to guard against these warning messages in the next release.

**Comment by djih** [comment]
@ileitch can I ask you what your use case is? The error is printed when you try to call an Amplitude function before you initialize. If you only enable it for certain builds, then shouldn't you only call the function if it is enabled?

**Comment by ileitch** [comment]
Our app delegate contains this:
```
- (void)configureAmplitude {
    NSString *apiKey;

#ifdef RELEASE_SCHEME
    apiKey = @"...";
#elif defined(ADHOC_ALPHA_SCHEME) || defined(ADHOC_BETA_SCHEME)
    apiKey = @"...";
#else
    // Uncomment to test Amplitude with debug builds.
    // apiKey = @"...";
#endif

    if (apiKey) {
        [[Amplitude instance] initializeApiKey:apiKey];
    }
}
```

To avoid the warning we would need to put a similar condition around every point that we trigger an event, which would not be ideal.

**Comment by djih** [comment]
You can disable error messages in v3.8.1: https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.8.1

**Comment by ileitch** [comment]
Thanks, but I think I'd rather just live with this minor annoyance than disabling _all_ error messages, I may silence something that's actually important.
